<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ejercicio_02</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="ejercicio_02_files/libs/clipboard/clipboard.min.js"></script>
<script src="ejercicio_02_files/libs/quarto-html/quarto.js"></script>
<script src="ejercicio_02_files/libs/quarto-html/popper.min.js"></script>
<script src="ejercicio_02_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ejercicio_02_files/libs/quarto-html/anchor.min.js"></script>
<link href="ejercicio_02_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ejercicio_02_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ejercicio_02_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ejercicio_02_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ejercicio_02_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<p>title: “Entrega de ejercicios Tema 3” author: “Blanca Cano Camarero” date: format: pdf: toc: true number-sections: true colorlinks: true toc-depth: 3</p>
<p>lang: es</p>
<hr>
<section id="ejercicio-2" class="level1">
<h1>Ejercicio 2</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'purrr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:magrittr':

    set_names</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>natalidad <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"https://verso.mat.uam.es/~joser.berrendero/datos/natalidad.txt"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log_pnb =</span> <span class="fu">log</span>(pnb))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(natalidad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   nat mort mortinf esph espm  pnb  log_pnb
1 24.7  5.7    30.8 69.6 75.5  600 6.396930
2 12.5 11.9    14.4 68.3 74.7 2250 7.718685
3 13.4 11.7    11.3 71.8 77.7 2980 7.999679
4 11.6 13.4    14.8 65.4 73.8 2780 7.930206
5 14.3 10.2    16.0 67.2 75.7 1690 7.432484
6 13.6 10.7    26.9 66.5 72.4 1640 7.402452</code></pre>
</div>
</div>
<p>Se desea estudiar la esperanza de vida de los hombres como función lineal de la tasa de natalidad, la tasa de mortalidad infantil y el logaritmo del producto nacional bruto. Para ello se ajusta un modelo de regresión lineal múltiple, con los resultados siguientes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(esph <span class="sc">~</span> nat  <span class="sc">+</span> mortinf <span class="sc">+</span> log_pnb, <span class="at">data =</span> natalidad)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = esph ~ nat + mortinf + log_pnb, data = natalidad)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.4893 -2.1660  0.1581  2.0663  7.9084 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 65.95088    3.25642  20.253  &lt; 2e-16 ***
nat         -0.14621    0.04762  -3.071  0.00285 ** 
mortinf     -0.13312    0.01537  -8.663  2.2e-13 ***
log_pnb      0.94478    0.32989   2.864  0.00524 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.128 on 87 degrees of freedom
Multiple R-squared:    0.9, Adjusted R-squared:  0.8966 
F-statistic: 261.1 on 3 and 87 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<section id="de-cuántos-países-consta-la-muestra-utilizada" class="level2">
<h2 class="anchored" data-anchor-id="de-cuántos-países-consta-la-muestra-utilizada">¿De cuántos países consta la muestra utilizada?</h2>
<p>Cada fila se corresponde con un país distinto luego habrá:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(natalidad)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>n</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 91</code></pre>
</div>
</div>
</section>
<section id="cuánto-vale-la-suma-de-cuadrados-que-se-utiliza-para-medir-la-variabilidad-explicada-por-las-tres-variables-regresoras" class="level2">
<h2 class="anchored" data-anchor-id="cuánto-vale-la-suma-de-cuadrados-que-se-utiliza-para-medir-la-variabilidad-explicada-por-las-tres-variables-regresoras">¿Cuánto vale la suma de cuadrados que se utiliza para medir la variabilidad explicada por las tres variables regresoras?</h2>
<p>Se busca calcular la suma de cuadrados explicada que se calcula como</p>
<p><span class="math display">\[
SCE
=
\sum_{i=1}^n
\left(
\hat{Y}_i - \bar{Y}
\right)^2.
\]</span></p>
<p>Este dato no aparece directamente en el <em>sumary</em> del la regresión lineal, luego habrá que calcularlo de manera manual.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>media_natalidad <span class="ot">&lt;-</span> <span class="fu">mean</span>(natalidad<span class="sc">$</span>nat)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">predict</span>(reg, natalidad)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>SCE <span class="ot">&lt;-</span> <span class="fu">Reduce</span>(<span class="st">'+'</span>,<span class="fu">map</span>(p, <span class="cf">function</span>(y_hat) (y_hat <span class="sc">-</span> media_natalidad)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"La suma de cuadrados resultante es"</span>,SCE, <span class="st">'</span><span class="sc">\n</span><span class="st">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La suma de cuadrados resultante es 100388.8 </code></pre>
</div>
</div>
</section>
<section id="cuánto-vale-la-varianza-muestral-de-la-variable-respuesta" class="level2">
<h2 class="anchored" data-anchor-id="cuánto-vale-la-varianza-muestral-de-la-variable-respuesta">¿Cuánto vale la varianza muestral de la variable respuesta ?</h2>
<p>Esta se define como <span class="math display">\[
VMR = \frac{1}{n-1}\sum_{i=1}^n
(Y_i - \bar Y)^2
\]</span></p>
<p>Que por definición de la suma de cuadrados total equivale a conocer la suma de cuadrados total (SCT)</p>
<p><span class="math display">\[
VMR = \frac{SCT}{n-1}
\]</span></p>
<p>Sabiendo que el coeficiente de determinación viene dado por <span class="math display">\[
r^2 = \frac{SCE}{SCT}
\]</span></p>
<p>Este valor se puede calcular como gracias a la información provista por el resumen de la regresión lineal</p>
<p><span class="math display">\[
r^2 = (\text{Multiple R-squared})^2 = 0.9^2 = 0.81.
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>r_squared <span class="ot">&lt;-</span> (<span class="fu">summary</span>(reg)<span class="sc">$</span>adj.r.squared)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>SCT <span class="ot">&lt;-</span> SCE <span class="sc">*</span> r_squared</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>VMR <span class="ot">=</span> SCT<span class="sc">/</span>(n<span class="dv">-1</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'VMR = '</span>, VMR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>VMR =  896.6372</code></pre>
</div>
</div>
</section>
<section id="contraste-de-la-complejidad-del-modelo" class="level2">
<h2 class="anchored" data-anchor-id="contraste-de-la-complejidad-del-modelo">Contraste de la complejidad del modelo</h2>
<p>Se desea que contrastar que <span class="math inline">\(H_0 : \beta_1 = 0\)</span><br>
esto viene determinado por el sistema matricial <span class="math inline">\(A\)</span> que es un vector fila con un uno en <span class="math inline">\(1\)</span> y el resto <span class="math inline">\(0\)</span>.</p>
<p>Debe de satisfacer que <span class="math inline">\(A \beta = 0\)</span>.</p>
<p>Definimos el modelo reducido <span class="math inline">\(M0\)</span> que resulta de imoner las restricciones de <span class="math inline">\(H_0\)</span>.</p>
<p>Bajo <span class="math inline">\(H_0: A \beta = 0\)</span> se verifica que</p>
<p><span class="math display">\[
\frac{
(SCR_0 - SCR) / k
}{
SCR / (n - p -1)
}
\equiv
F_{k,n-p-1},
\]</span> donde <span class="math inline">\(k\)</span> es el número de restricciones (rango de <span class="math inline">\(A\)</span> ciertamente), <span class="math inline">\(p+1\)</span> el número de <span class="math inline">\(\beta\)</span> (variables del modelo a ajustar) y <span class="math inline">\(n\)</span> el número de observaciones.</p>
<p>La región crítica del contraste para nivel <span class="math inline">\(\alpha\)</span> es</p>
<p><span class="math display">\[
R
=
\left\{
\frac{
(SCR_0 - SCR) / k
}{
SCR / (n - p -1)
}
&gt;
F_{k,n-p-1}
\right\}
\]</span></p>
<p>Utilizaremos el comando <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/anova"><code>anova</code></a> para R.</p>
</section>
<section id="contrasta-a-nivel-alpha-0.05-la-hipótesis-nula-h_0-beta_1-0" class="level2">
<h2 class="anchored" data-anchor-id="contrasta-a-nivel-alpha-0.05-la-hipótesis-nula-h_0-beta_1-0">Contrasta a nivel <span class="math inline">\(\alpha = 0.05\)</span> la hipótesis nula <span class="math inline">\(H_0 : \beta_1 = 0\)</span></h2>
<p><strong>Solución</strong></p>
<p>Al suponer que <span class="math inline">\(\beta_1 = 0\)</span> entonces ahora el modelo precindiría de natalidad, esto sería ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>reg0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(esph <span class="sc">~</span>  mortinf <span class="sc">+</span> log_pnb, <span class="at">data =</span> natalidad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>:::</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(reg0, reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: esph ~ mortinf + log_pnb
Model 2: esph ~ nat + mortinf + log_pnb
  Res.Df    RSS Df Sum of Sq      F  Pr(&gt;F)   
1     88 943.73                               
2     87 851.46  1    92.277 9.4286 0.00285 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>De aquí deducimos que la región crítica <span class="math inline">\(F = 9.411\)</span> y lo que buscábamos, que la probabilidad de pertenecer a la región crítica siendo la <span class="math inline">\(H_0\)</span> cierta es de</p>
<p><span class="math display">\[
Pr(&gt;F) = 0.00285
\]</span></p>
<p>Como $ 0.00285 &lt; 0.05$ rechazamos entonces la hipótesis nula.</p>
</section>
<section id="contrasta-a-nivel-alpha-0.05-la-hipótesis-nula-h_0-beta_1-beta_2-beta_3-0" class="level2">
<h2 class="anchored" data-anchor-id="contrasta-a-nivel-alpha-0.05-la-hipótesis-nula-h_0-beta_1-beta_2-beta_3-0">Contrasta a nivel <span class="math inline">\(\alpha = 0.05\)</span> la hipótesis nula <span class="math inline">\(H_0 : \beta_1 = \beta_2 = \beta_3 =0\)</span></h2>
<p>Contrasteremos que solo se pueda aproximar con la media</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>reg0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(esph <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> natalidad) <span class="co"># ahora sería solo con la media</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(reg0, reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: esph ~ 1
Model 2: esph ~ nat + mortinf + log_pnb
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1     90 8516.5                                  
2     87  851.5  3    7665.1 261.07 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Como podemos observar, ahora</p>
<p><span class="math display">\[
Pr(&gt;F)   &lt; 2.2e-16
\]</span></p>
<p>es decir prácticamente <span class="math inline">\(0\)</span> luego se rechaza la hipótesis nula.</p>
<p>Ya que si la media fuera un buen estimador se podría pensar que los modelos no tienen nada que ver con el modelo.</p>
</section>
<section id="estima-la-correlación-entre-hatbeta_1-y-hatbeta_2." class="level2">
<h2 class="anchored" data-anchor-id="estima-la-correlación-entre-hatbeta_1-y-hatbeta_2.">Estima la correlación entre <span class="math inline">\(\hat{\beta}_1\)</span> y <span class="math inline">\(\hat{\beta}_2\)</span>.</h2>
<p>Esto se hará con el comando <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/vcov"><code>vcoc</code></a> que devuelve la matriz de covarianza de los parámetros ajustados.</p>
<p><span class="math inline">\(\hat{\beta}_1\)</span> se corresponde a <code>nat</code> y <span class="math inline">\(\hat{\beta}_2\)</span> se corresponde con <code>mortinf</code> luego mirando la respectiva fila y columan tenemos que</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vcov</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            (Intercept)           nat       mortinf      log_pnb
(Intercept) 10.60424770 -0.0636441427 -0.0154732224 -1.033908908
nat         -0.06364414  0.0022673659 -0.0004865478  0.003160908
mortinf     -0.01547322 -0.0004865478  0.0002361416  0.002230265
log_pnb     -1.03390891  0.0031609079  0.0022302652  0.108830676</code></pre>
</div>
</div>
<p><span class="math display">\[
cov(\hat{\beta}_1, \hat{\beta}_2)
=
-0.0004865478
\]</span></p>
<p>Puesto que el restultano es cercano a <span class="math inline">\(0\)</span> podemos pensar que el signo de una es independiente del de la otra, es decir independientes.</p>
<p>Por lo tanto apriori no podríamos explicar una varia con la otra con un modelo lineal.</p>
</section>
<section id="calcula-intervalos-de-confianza-al-nivel-90-para-todos-los-beta_i-del-modelo." class="level2">
<h2 class="anchored" data-anchor-id="calcula-intervalos-de-confianza-al-nivel-90-para-todos-los-beta_i-del-modelo.">Calcula intervalos de confianza al nivel <span class="math inline">\(90\%\)</span> para todos los <span class="math inline">\(\beta_i\)</span> del modelo.</h2>
<p>Usaremos la función <a href="https://fhernanb.github.io/libro_regresion/ic.html"><code>confint</code></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(reg, <span class="at">level=</span><span class="fl">0.90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   5 %        95 %
(Intercept) 60.5369009 71.36485887
nat         -0.2253786 -0.06704702
mortinf     -0.1586652 -0.10756848
log_pnb      0.3963072  1.49324572</code></pre>
</div>
</div>
<p>esto no da un rango de incertidumbre en el que puede oscilar cada uno de los respectivos parámetros con un <span class="math inline">\(90 \%\)</span> de probabilidad.</p>
<p><span class="math display">\[
\begin{align}
&amp;\beta_{0} \in [60.537, 71.365], \\
&amp;\beta_{\text{ nat}} \in [-0.225 -0.067], \\
&amp;\beta_{\text{mortinf}} \in [-0.158, -0.108], \\
&amp;\beta_{\text{ log_pnb }}  \in [0.396 , 1.493]. \\
\end{align}
\]</span> Ya <span class="math display">\[
P( \beta_{inf} \leq \beta \leq \beta_{sup}) = 1 - \alpha.
\]</span> Donde <span class="math inline">\(\beta_{inf}\)</span> y <span class="math inline">\(\beta_{sup}\)</span> son los elementos inferiores y superiores del intervalo.</p>
<p>Cuando mayor sea el intervalo más incertidumbre tendremos de la corrección del parámetro.</p>
</section>
<section id="predice-el-valor-de-la-esperanza-de-vida-de-los-hombres-en-un-país-para-el-que-el-índice-de-natalidad-es-29-la-mortalidad-infantil-vale-50-y-el-logaritmo-de-su-pnb-vale-7.-calcula-un-intervalo-de-confianza-del-95-para-el-valor-esperado-de-dicha-variable." class="level2">
<h2 class="anchored" data-anchor-id="predice-el-valor-de-la-esperanza-de-vida-de-los-hombres-en-un-país-para-el-que-el-índice-de-natalidad-es-29-la-mortalidad-infantil-vale-50-y-el-logaritmo-de-su-pnb-vale-7.-calcula-un-intervalo-de-confianza-del-95-para-el-valor-esperado-de-dicha-variable.">Predice el valor de la esperanza de vida de los hombres en un país para el que el índice de natalidad es 29, la mortalidad infantil vale 50 y el logaritmo de su pnb vale 7. Calcula un intervalo de confianza del 95 % para el valor esperado de dicha variable.</h2>
<p>Para ello usaremos la función <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/predict.lm"><code>predict</code></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Debemos de escribir el data frame con el nombre exacto </span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co">#bde las columnas con las que se creo el modelo de regresión.</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Estas son:</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># nat     mortinf     log_pnb </span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>new_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">nat =</span> <span class="dv">29</span>,</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">mortinf =</span> <span class="dv">50</span>,</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">log_pnb =</span> <span class="dv">7</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizamos la predicción </span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(reg, new_data, <span class="at">interval =</span> <span class="st">"confidence"</span>, <span class="at">level =</span> <span class="fl">0.95</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      fit      lwr    upr
1 61.6683 60.88761 62.449</code></pre>
</div>
</div>
<p>Por lo tanto la esperanza de visa de los hombres de ese pais es de 61.6683 años. El intervalo de confianza es de <span class="math inline">\([60.88761, 62.449]\)</span> es decir valores sobre los que podría oscilar el valor con un <span class="math inline">\(95 \%\)</span> de confianza.</p>
<p>Además cabe mencionar que la predicción del intervalo se basa en que el error residual están distribuidos bajo una distribución normal y varianza constante. Luego solo deberíamos de usar estos intervalos si tuvieramos razones para pensar que se da esta condición.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>