<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>entrega</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="entrega_files/libs/clipboard/clipboard.min.js"></script>
<script src="entrega_files/libs/quarto-html/quarto.js"></script>
<script src="entrega_files/libs/quarto-html/popper.min.js"></script>
<script src="entrega_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="entrega_files/libs/quarto-html/anchor.min.js"></script>
<link href="entrega_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="entrega_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="entrega_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="entrega_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="entrega_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<p>title: “Entrega de ejercicios Tema 3” author: “Blanca Cano Camarero” date: format: pdf: toc: true number-sections: true colorlinks: true toc-depth: 3</p>
<p>lang: es</p>
<hr>
<section id="ejercicio-2" class="level1">
<h1>Ejercicio 2</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'purrr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:magrittr':

    set_names</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>natalidad <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"https://verso.mat.uam.es/~joser.berrendero/datos/natalidad.txt"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log_pnb =</span> <span class="fu">log</span>(pnb))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(natalidad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   nat mort mortinf esph espm  pnb  log_pnb
1 24.7  5.7    30.8 69.6 75.5  600 6.396930
2 12.5 11.9    14.4 68.3 74.7 2250 7.718685
3 13.4 11.7    11.3 71.8 77.7 2980 7.999679
4 11.6 13.4    14.8 65.4 73.8 2780 7.930206
5 14.3 10.2    16.0 67.2 75.7 1690 7.432484
6 13.6 10.7    26.9 66.5 72.4 1640 7.402452</code></pre>
</div>
</div>
<p>Se desea estudiar la esperanza de vida de los hombres como función lineal de la tasa de natalidad, la tasa de mortalidad infantil y el logaritmo del producto nacional bruto. Para ello se ajusta un modelo de regresión lineal múltiple, con los resultados siguientes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(esph <span class="sc">~</span> nat  <span class="sc">+</span> mortinf <span class="sc">+</span> log_pnb, <span class="at">data =</span> natalidad)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = esph ~ nat + mortinf + log_pnb, data = natalidad)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.4893 -2.1660  0.1581  2.0663  7.9084 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 65.95088    3.25642  20.253  &lt; 2e-16 ***
nat         -0.14621    0.04762  -3.071  0.00285 ** 
mortinf     -0.13312    0.01537  -8.663  2.2e-13 ***
log_pnb      0.94478    0.32989   2.864  0.00524 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.128 on 87 degrees of freedom
Multiple R-squared:    0.9, Adjusted R-squared:  0.8966 
F-statistic: 261.1 on 3 and 87 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<section id="de-cuántos-países-consta-la-muestra-utilizada" class="level2">
<h2 class="anchored" data-anchor-id="de-cuántos-países-consta-la-muestra-utilizada">¿De cuántos países consta la muestra utilizada?</h2>
<p>Cada fila se corresponde con un país distinto luego habrá:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(natalidad)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>n</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 91</code></pre>
</div>
</div>
</section>
<section id="cuánto-vale-la-suma-de-cuadrados-que-se-utiliza-para-medir-la-variabilidad-explicada-por-las-tres-variables-regresoras" class="level2">
<h2 class="anchored" data-anchor-id="cuánto-vale-la-suma-de-cuadrados-que-se-utiliza-para-medir-la-variabilidad-explicada-por-las-tres-variables-regresoras">¿Cuánto vale la suma de cuadrados que se utiliza para medir la variabilidad explicada por las tres variables regresoras?</h2>
<p>Se busca calcular la suma de cuadrados explicada que se calcula como</p>
<p><span class="math display">\[
SCE
=
\sum_{i=1}^n
\left(
\hat{Y}_i - \bar{Y}
\right)^2.
\]</span></p>
<p>Este dato no aparece directamente en el <em>sumary</em> del la regresión lineal, luego habrá que calcularlo de manera manual.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>media_natalidad <span class="ot">&lt;-</span> <span class="fu">mean</span>(natalidad<span class="sc">$</span>nat)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">predict</span>(reg, natalidad)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>SCE <span class="ot">&lt;-</span> <span class="fu">Reduce</span>(<span class="st">'+'</span>,<span class="fu">map</span>(p, <span class="cf">function</span>(y_hat) (y_hat <span class="sc">-</span> media_natalidad)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"La suma de cuadrados resultante es"</span>,SCE, <span class="st">'</span><span class="sc">\n</span><span class="st">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La suma de cuadrados resultante es 100388.8 </code></pre>
</div>
</div>
</section>
<section id="cuánto-vale-la-varianza-muestral-de-la-variable-respuesta" class="level2">
<h2 class="anchored" data-anchor-id="cuánto-vale-la-varianza-muestral-de-la-variable-respuesta">¿Cuánto vale la varianza muestral de la variable respuesta ?</h2>
<p>Esta se define como <span class="math display">\[
VMR = \frac{1}{n-1}\sum_{i=1}^n
(Y_i - \bar Y)^2
\]</span></p>
<p>Que por definición de la suma de cuadrados total equivale a conocer la suma de cuadrados total (SCT)</p>
<p><span class="math display">\[
VMR = \frac{SCT}{n-1}
\]</span></p>
<p>Sabiendo que el coeficiente de determinación viene dado por <span class="math display">\[
r^2 = \frac{SCE}{SCT}
\]</span></p>
<p>Este valor se puede calcular como gracias a la información provista por el resumen de la regresión lineal</p>
<p><span class="math display">\[
r^2 = (\text{Multiple R-squared})^2 = 0.9^2 = 0.81.
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>r_squared <span class="ot">&lt;-</span> (<span class="fu">summary</span>(reg)<span class="sc">$</span>adj.r.squared)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>SCT <span class="ot">&lt;-</span> SCE <span class="sc">*</span> r_squared</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>VMR <span class="ot">=</span> SCT<span class="sc">/</span>(n<span class="dv">-1</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'VMR = '</span>, VMR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>VMR =  896.6372</code></pre>
</div>
</div>
</section>
<section id="contraste-de-la-complejidad-del-modelo" class="level2">
<h2 class="anchored" data-anchor-id="contraste-de-la-complejidad-del-modelo">Contraste de la complejidad del modelo</h2>
<p>Se desea que contrastar que <span class="math inline">\(H_0 : \beta_1 = 0\)</span><br>
esto viene determinado por el sistema matricial <span class="math inline">\(A\)</span> que es un vector fila con un uno en <span class="math inline">\(1\)</span> y el resto <span class="math inline">\(0\)</span>.</p>
<p>Debe de satisfacer que <span class="math inline">\(A \beta = 0\)</span>.</p>
<p>Definimos el modelo reducido <span class="math inline">\(M0\)</span> que resulta de imoner las restricciones de <span class="math inline">\(H_0\)</span>.</p>
<p>Bajo <span class="math inline">\(H_0: A \beta = 0\)</span> se verifica que</p>
<p><span class="math display">\[
\frac{
(SCR_0 - SCR) / k
}{
SCR / (n - p -1)
}
\equiv
F_{k,n-p-1},
\]</span> donde <span class="math inline">\(k\)</span> es el número de restricciones (rango de <span class="math inline">\(A\)</span> ciertamente), <span class="math inline">\(p+1\)</span> el número de <span class="math inline">\(\beta\)</span> (variables del modelo a ajustar) y <span class="math inline">\(n\)</span> el número de observaciones.</p>
<p>La región crítica del contraste para nivel <span class="math inline">\(\alpha\)</span> es</p>
<p><span class="math display">\[
R
=
\left\{
\frac{
(SCR_0 - SCR) / k
}{
SCR / (n - p -1)
}
&gt;
F_{k,n-p-1}
\right\}
\]</span></p>
<p>Utilizaremos el comando <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/anova"><code>anova</code></a> para R.</p>
</section>
<section id="contrasta-a-nivel-alpha-0.05-la-hipótesis-nula-h_0-beta_1-0" class="level2">
<h2 class="anchored" data-anchor-id="contrasta-a-nivel-alpha-0.05-la-hipótesis-nula-h_0-beta_1-0">Contrasta a nivel <span class="math inline">\(\alpha = 0.05\)</span> la hipótesis nula <span class="math inline">\(H_0 : \beta_1 = 0\)</span></h2>
<p><strong>Solución</strong></p>
<p>Al suponer que <span class="math inline">\(\beta_1 = 0\)</span> entonces ahora el modelo precindiría de natalidad, esto sería ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>reg0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(esph <span class="sc">~</span>  mortinf <span class="sc">+</span> log_pnb, <span class="at">data =</span> natalidad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>:::</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(reg0, reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: esph ~ mortinf + log_pnb
Model 2: esph ~ nat + mortinf + log_pnb
  Res.Df    RSS Df Sum of Sq      F  Pr(&gt;F)   
1     88 943.73                               
2     87 851.46  1    92.277 9.4286 0.00285 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>De aquí deducimos que la región crítica <span class="math inline">\(F = 9.411\)</span> y lo que buscábamos, que la probabilidad de pertenecer a la región crítica siendo la <span class="math inline">\(H_0\)</span> cierta es de</p>
<p><span class="math display">\[
Pr(&gt;F) = 0.00285
\]</span></p>
<p>Como $ 0.00285 &lt; 0.05$ rechazamos entonces la hipótesis nula.</p>
</section>
<section id="contrasta-a-nivel-alpha-0.05-la-hipótesis-nula-h_0-beta_1-beta_2-beta_3-0" class="level2">
<h2 class="anchored" data-anchor-id="contrasta-a-nivel-alpha-0.05-la-hipótesis-nula-h_0-beta_1-beta_2-beta_3-0">Contrasta a nivel <span class="math inline">\(\alpha = 0.05\)</span> la hipótesis nula <span class="math inline">\(H_0 : \beta_1 = \beta_2 = \beta_3 =0\)</span></h2>
<p>Contrasteremos que solo se pueda aproximar con la media</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>reg0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(esph <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> natalidad) <span class="co"># ahora sería solo con la media</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(reg0, reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: esph ~ 1
Model 2: esph ~ nat + mortinf + log_pnb
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1     90 8516.5                                  
2     87  851.5  3    7665.1 261.07 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Como podemos observar, ahora</p>
<p><span class="math display">\[
Pr(&gt;F)   &lt; 2.2e-16
\]</span></p>
<p>es decir prácticamente <span class="math inline">\(0\)</span> luego se rechaza la hipótesis nula.</p>
<p>Ya que si la media fuera un buen estimador se podría pensar que los modelos no tienen nada que ver con el modelo.</p>
</section>
<section id="estima-la-correlación-entre-hatbeta_1-y-hatbeta_2." class="level2">
<h2 class="anchored" data-anchor-id="estima-la-correlación-entre-hatbeta_1-y-hatbeta_2.">Estima la correlación entre <span class="math inline">\(\hat{\beta}_1\)</span> y <span class="math inline">\(\hat{\beta}_2\)</span>.</h2>
<p>Esto se hará con el comando <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/vcov"><code>vcoc</code></a> que devuelve la matriz de covarianza de los parámetros ajustados.</p>
<p><span class="math inline">\(\hat{\beta}_1\)</span> se corresponde a <code>nat</code> y <span class="math inline">\(\hat{\beta}_2\)</span> se corresponde con <code>mortinf</code> luego mirando la respectiva fila y columan tenemos que</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vcov</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            (Intercept)           nat       mortinf      log_pnb
(Intercept) 10.60424770 -0.0636441427 -0.0154732224 -1.033908908
nat         -0.06364414  0.0022673659 -0.0004865478  0.003160908
mortinf     -0.01547322 -0.0004865478  0.0002361416  0.002230265
log_pnb     -1.03390891  0.0031609079  0.0022302652  0.108830676</code></pre>
</div>
</div>
<p><span class="math display">\[
cov(\hat{\beta}_1, \hat{\beta}_2)
=
-0.0004865478
\]</span></p>
<p>Puesto que el restultano es cercano a <span class="math inline">\(0\)</span> podemos pensar que el signo de una es independiente del de la otra, es decir independientes.</p>
<p>Por lo tanto apriori no podríamos explicar una varia con la otra con un modelo lineal.</p>
</section>
<section id="calcula-intervalos-de-confianza-al-nivel-90-para-todos-los-beta_i-del-modelo." class="level2">
<h2 class="anchored" data-anchor-id="calcula-intervalos-de-confianza-al-nivel-90-para-todos-los-beta_i-del-modelo.">Calcula intervalos de confianza al nivel <span class="math inline">\(90\%\)</span> para todos los <span class="math inline">\(\beta_i\)</span> del modelo.</h2>
<p>Usaremos la función <a href="https://fhernanb.github.io/libro_regresion/ic.html"><code>confint</code></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(reg, <span class="at">level=</span><span class="fl">0.90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   5 %        95 %
(Intercept) 60.5369009 71.36485887
nat         -0.2253786 -0.06704702
mortinf     -0.1586652 -0.10756848
log_pnb      0.3963072  1.49324572</code></pre>
</div>
</div>
<p>esto no da un rango de incertidumbre en el que puede oscilar cada uno de los respectivos parámetros con un <span class="math inline">\(90 \%\)</span> de probabilidad.</p>
<p><span class="math display">\[
\begin{align}
&amp;\beta_{0} \in [60.537, 71.365], \\
&amp;\beta_{\text{ nat}} \in [-0.225 -0.067], \\
&amp;\beta_{\text{mortinf}} \in [-0.158, -0.108], \\
&amp;\beta_{\text{ log_pnb }}  \in [0.396 , 1.493]. \\
\end{align}
\]</span> Ya <span class="math display">\[
P( \beta_{inf} \leq \beta \leq \beta_{sup}) = 1 - \alpha.
\]</span> Donde <span class="math inline">\(\beta_{inf}\)</span> y <span class="math inline">\(\beta_{sup}\)</span> son los elementos inferiores y superiores del intervalo.</p>
<p>Cuando mayor sea el intervalo más incertidumbre tendremos de la corrección del parámetro.</p>
</section>
<section id="predice-el-valor-de-la-esperanza-de-vida-de-los-hombres-en-un-país-para-el-que-el-índice-de-natalidad-es-29-la-mortalidad-infantil-vale-50-y-el-logaritmo-de-su-pnb-vale-7.-calcula-un-intervalo-de-confianza-del-95-para-el-valor-esperado-de-dicha-variable." class="level2">
<h2 class="anchored" data-anchor-id="predice-el-valor-de-la-esperanza-de-vida-de-los-hombres-en-un-país-para-el-que-el-índice-de-natalidad-es-29-la-mortalidad-infantil-vale-50-y-el-logaritmo-de-su-pnb-vale-7.-calcula-un-intervalo-de-confianza-del-95-para-el-valor-esperado-de-dicha-variable.">Predice el valor de la esperanza de vida de los hombres en un país para el que el índice de natalidad es 29, la mortalidad infantil vale 50 y el logaritmo de su pnb vale 7. Calcula un intervalo de confianza del 95 % para el valor esperado de dicha variable.</h2>
<p>Para ello usaremos la función <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/predict.lm"><code>predict</code></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Debemos de escribir el data frame con el nombre exacto </span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co">#bde las columnas con las que se creo el modelo de regresión.</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Estas son:</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># nat     mortinf     log_pnb </span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>new_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">nat =</span> <span class="dv">29</span>,</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">mortinf =</span> <span class="dv">50</span>,</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">log_pnb =</span> <span class="dv">7</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizamos la predicción </span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(reg, new_data, <span class="at">interval =</span> <span class="st">"confidence"</span>, <span class="at">level =</span> <span class="fl">0.95</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      fit      lwr    upr
1 61.6683 60.88761 62.449</code></pre>
</div>
</div>
<p>Por lo tanto la esperanza de visa de los hombres de ese pais es de 61.6683 años. El intervalo de confianza es de <span class="math inline">\([60.88761, 62.449]\)</span> es decir valores sobre los que podría oscilar el valor con un <span class="math inline">\(95 \%\)</span> de confianza.</p>
<p>Además cabe mencionar que la predicción del intervalo se basa en que el error residual están distribuidos bajo una distribución normal y varianza constante. Luego solo deberíamos de usar estos intervalos si tuvieramos razones para pensar que se da esta condición.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="ejercicio-9" class="level1">
<h1>Ejercicio 9</h1>
<p>Genera aleatoriamente una variable regresora <span class="math inline">\(X\)</span> y un vector aleatorio <span class="math inline">\(\epsilon\)</span> de longitud <span class="math inline">\(n = 100\)</span>, con distribución normal estándar e independientes.</p>
<p>Genera la variable respuesta de acuerdo con el modelo: <span class="math display">\[
Y = X + X^2 + X^3 + \epsilon.
\]</span> ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ramify)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'ramify'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    flatten</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:graphics':

    clip</code></pre>
</div>
<p>:::</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>X_distribution <span class="ot">&lt;-</span> rnorm </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>error_distribution <span class="ot">&lt;-</span> rnorm</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>modelo_1 <span class="ot">&lt;-</span> <span class="cf">function</span> (x) {</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span> (x <span class="sc">+</span> x<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> x<span class="sc">^</span><span class="dv">3</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>Y_distribution <span class="ot">&lt;-</span> <span class="cf">function</span> (n, t){</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">X_distribution</span>(n)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  e <span class="ot">&lt;-</span> <span class="fu">error_distribution</span>(n)</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span> (<span class="fu">sapply</span>(x, t) <span class="sc">+</span> e)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>Y_1 <span class="ot">&lt;-</span> <span class="fu">Y_distribution</span>(n, modelo_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">X_distribution</span>(n)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Generamos las potencias</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="st">'1'</span><span class="ot">=</span>X)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">10</span>) {</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  datos[i] <span class="ot">&lt;-</span> datos[<span class="dv">1</span>]<span class="sc">*</span>datos[i<span class="dv">-1</span>]</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo1 </span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="fu">unlist</span>(<span class="fu">as.list</span>(datos[<span class="dv">1</span>]<span class="sc">+</span>datos[<span class="dv">2</span>] <span class="sc">+</span> datos[<span class="dv">3</span>] <span class="sc">+</span> <span class="fu">error_distribution</span>(n)))</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>datos<span class="sc">$</span><span class="st">'y'</span> <span class="ot">&lt;-</span> Y</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>datos</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              X1         X1.1          X1.2         X1.3          X1.4
1   -0.146150014 2.135983e-02 -3.121739e-03 4.562422e-04 -6.667980e-05
2   -0.685004253 4.692308e-01 -3.214251e-01 2.201776e-01 -1.508226e-01
3    1.103044432 1.216707e+00  1.342082e+00 1.480376e+00  1.632920e+00
4   -0.931186667 8.671086e-01 -8.074400e-01 7.518773e-01 -7.001382e-01
5    1.252107859 1.567774e+00  1.963022e+00 2.457916e+00  3.077575e+00
6   -1.981411263 3.925991e+00 -7.779002e+00 1.541340e+01 -3.054029e+01
7   -0.507018950 2.570682e-01 -1.303385e-01 6.608407e-02 -3.350587e-02
8    0.840258385 7.060342e-01  5.932511e-01 4.984842e-01  4.188555e-01
9   -0.097712944 9.547820e-03 -9.329456e-04 9.116086e-05 -8.907596e-06
10   0.323326386 1.045400e-01  3.380052e-02 1.092860e-02  3.533505e-03
11  -1.455612063 2.118806e+00 -3.084160e+00 4.489341e+00 -6.534739e+00
12   0.378110199 1.429673e-01  5.405740e-02 2.043966e-02  7.728442e-03
13   1.345569918 1.810558e+00  2.436233e+00 3.278122e+00  4.410942e+00
14   0.852266620 7.263584e-01  6.190510e-01 5.275965e-01  4.496529e-01
15   1.315428738 1.730353e+00  2.276156e+00 2.994121e+00  3.938552e+00
16   0.497067779 2.470764e-01  1.228137e-01 6.104674e-02  3.034437e-02
17   1.589455303 2.526368e+00  4.015549e+00 6.382536e+00  1.014476e+01
18   2.051545132 4.208837e+00  8.634620e+00 1.771431e+01  3.634171e+01
19   0.870830367 7.583455e-01  6.603903e-01 5.750879e-01  5.008040e-01
20  -1.473055257 2.169892e+00 -3.196371e+00 4.708430e+00 -6.935778e+00
21   0.197471759 3.899510e-02  7.700430e-03 1.520617e-03  3.002790e-04
22   2.021351255 4.085861e+00  8.258960e+00 1.669426e+01  3.374496e+01
23  -0.227315782 5.167246e-02 -1.174597e-02 2.670044e-03 -6.069431e-04
24   0.542034183 2.938011e-01  1.592502e-01 8.631906e-02  4.678788e-02
25   0.244716550 5.988619e-02  1.465514e-02 3.586356e-03  8.776406e-04
26  -0.644901366 4.158978e-01 -2.682130e-01 1.729710e-01 -1.115492e-01
27  -0.394583067 1.556958e-01 -6.143493e-02 2.424118e-02 -9.565160e-03
28  -0.469888874 2.207956e-01 -1.037494e-01 4.875068e-02 -2.290740e-02
29  -0.923771543 8.533539e-01 -7.883040e-01 7.282128e-01 -6.727023e-01
30  -0.999600253 9.992007e-01 -9.988012e-01 9.984020e-01 -9.980029e-01
31  -0.173036833 2.994175e-02 -5.181025e-03 8.965081e-04 -1.551289e-04
32  -0.557357770 3.106477e-01 -1.731419e-01 9.650198e-02 -5.378613e-02
33  -0.260156036 6.768116e-02 -1.760766e-02 4.580740e-03 -1.191707e-03
34  -0.424850525 1.804980e-01 -7.668466e-02 3.257952e-02 -1.384142e-02
35   0.388256077 1.507428e-01  5.852680e-02 2.272339e-02  8.822493e-03
36   1.607644430 2.584521e+00  4.154990e+00 6.679747e+00  1.073866e+01
37  -0.677795496 4.594067e-01 -3.113838e-01 2.110545e-01 -1.430518e-01
38  -0.367396344 1.349801e-01 -4.959119e-02 1.821962e-02 -6.693822e-03
39   1.147019322 1.315653e+00  1.509080e+00 1.730944e+00  1.985426e+00
40  -0.564853818 3.190598e-01 -1.802222e-01 1.017992e-01 -5.750165e-02
41  -0.728763899 5.310968e-01 -3.870442e-01 2.820638e-01 -2.055579e-01
42   0.973928638 9.485370e-01  9.238073e-01 8.997224e-01  8.762654e-01
43  -1.598280163 2.554499e+00 -4.082806e+00 6.525468e+00 -1.042953e+01
44  -1.503535349 2.260619e+00 -3.398920e+00 5.110396e+00 -7.683661e+00
45   0.146959858 2.159720e-02  3.173921e-03 4.664390e-04  6.854782e-05
46   0.022512313 5.068042e-04  1.140934e-05 2.568505e-07  5.782299e-09
47   1.644755410 2.705220e+00  4.449426e+00 7.318217e+00  1.203668e+01
48   2.584354249 6.678887e+00  1.726061e+01 4.460753e+01  1.152817e+02
49  -0.732966994 5.372406e-01 -3.937796e-01 2.886275e-01 -2.115544e-01
50  -0.855876444 7.325245e-01 -6.269505e-01 5.365921e-01 -4.592566e-01
51  -1.381963165 1.909822e+00 -2.639304e+00 3.647421e+00 -5.040601e+00
52  -0.915488955 8.381200e-01 -7.672896e-01 7.024452e-01 -6.430808e-01
53   1.160693583 1.347210e+00  1.563698e+00 1.814974e+00  2.106628e+00
54   0.869139636 7.554037e-01  6.565513e-01 5.706348e-01  4.959613e-01
55   1.246380431 1.553464e+00  1.936207e+00 2.413251e+00  3.007829e+00
56   0.087067516 7.580752e-03  6.600373e-04 5.746781e-05  5.003579e-06
57   0.858019055 7.361967e-01  6.316708e-01 5.419856e-01  4.650340e-01
58   1.067383734 1.139308e+00  1.216079e+00 1.298023e+00  1.385488e+00
59  -1.052528149 1.107816e+00 -1.166007e+00 1.227255e+00 -1.291721e+00
60  -0.383233864 1.468682e-01 -5.628487e-02 2.157027e-02 -8.266457e-03
61   0.134976161 1.821856e-02  2.459072e-03 3.319161e-04  4.480076e-05
62   0.101593199 1.032118e-02  1.048562e-03 1.065267e-04  1.082239e-05
63  -0.059760016 3.571259e-03 -2.134185e-04 1.275389e-05 -7.621729e-07
64  -0.293034867 8.586943e-02 -2.516274e-02 7.373560e-03 -2.160710e-03
65  -0.522369877 2.728703e-01 -1.425392e-01 7.445819e-02 -3.889472e-02
66   0.538420700 2.898969e-01  1.560865e-01 8.404018e-02  4.524897e-02
67   0.817156102 6.677441e-01  5.456512e-01 4.458822e-01  3.643553e-01
68  -0.555993307 3.091286e-01 -1.718734e-01 9.556047e-02 -5.313098e-02
69   1.142955631 1.306348e+00  1.493097e+00 1.706544e+00  1.950504e+00
70  -0.362368926 1.313112e-01 -4.758311e-02 1.724264e-02 -6.248197e-03
71  -0.002157968 4.656824e-06 -1.004928e-08 2.168601e-11 -4.679771e-14
72   0.861181537 7.416336e-01  6.386812e-01 5.500205e-01  4.736675e-01
73  -1.270702655 1.614685e+00 -2.051785e+00 2.607208e+00 -3.312987e+00
74  -1.322434952 1.748834e+00 -2.312719e+00 3.058421e+00 -4.044563e+00
75  -0.152741242 2.332989e-02 -3.563436e-03 5.442836e-04 -8.313456e-05
76   1.314627936 1.728247e+00  2.272001e+00 2.986836e+00  3.926579e+00
77   0.005538859 3.067896e-05  1.699264e-07 9.411984e-10  5.213165e-12
78   0.060703543 3.684920e-03  2.236877e-04 1.357864e-05  8.242713e-07
79  -1.643207561 2.700131e+00 -4.436876e+00 7.290708e+00 -1.198015e+01
80   1.922135184 3.694604e+00  7.101528e+00 1.365010e+01  2.623733e+01
81   2.162242722 4.675294e+00  1.010912e+01 2.185837e+01  4.726310e+01
82   1.718452766 2.953080e+00  5.074728e+00 8.720681e+00  1.498608e+01
83   0.020944965 4.386916e-04  9.188379e-06 1.924503e-07  4.030865e-09
84  -0.530094243 2.809999e-01 -1.489564e-01 7.896095e-02 -4.185674e-02
85  -1.733773810 3.005972e+00 -5.211675e+00 9.035865e+00 -1.566615e+01
86   1.420847749 2.018808e+00  2.868419e+00 4.075587e+00  5.790789e+00
87   0.110533608 1.221768e-02  1.350464e-03 1.492717e-04  1.649954e-05
88   0.262366097 6.883597e-02  1.806022e-02 4.738391e-03  1.243193e-03
89   1.157707358 1.340286e+00  1.551659e+00 1.796367e+00  2.079668e+00
90  -0.869022174 7.551995e-01 -6.562851e-01 5.703263e-01 -4.956262e-01
91  -1.411699465 1.992895e+00 -2.813369e+00 3.971632e+00 -5.606751e+00
92  -0.761696683 5.801818e-01 -4.419226e-01 3.366110e-01 -2.563955e-01
93  -2.696792601 7.272690e+00 -1.961294e+01 5.289202e+01 -1.426388e+02
94  -2.047462838 4.192104e+00 -8.583177e+00 1.757374e+01 -3.598157e+01
95   1.491455974 2.224441e+00  3.317656e+00 4.948137e+00  7.379929e+00
96  -0.789693231 6.236154e-01 -4.924649e-01 3.888962e-01 -3.071087e-01
97   0.267074955 7.132903e-02  1.905020e-02 5.087831e-03  1.358832e-03
98  -2.221315401 4.934242e+00 -1.096051e+01 2.434675e+01 -5.408180e+01
99   0.690116074 4.762602e-01  3.286748e-01 2.268238e-01  1.565347e-01
100 -0.212645899 4.521828e-02 -9.615481e-03 2.044693e-03 -4.347955e-04
            X1.5          X1.6         X1.7          X1.8         X1.9
1   9.745254e-06 -1.424269e-06 2.081569e-07 -3.042214e-08 4.446196e-09
2   1.033141e-01 -7.077060e-02 4.847816e-02 -3.320775e-02 2.274745e-02
3   1.801184e+00  1.986786e+00 2.191513e+00  2.417336e+00 2.666429e+00
4   6.519593e-01 -6.070958e-01 5.653195e-01 -5.264180e-01 4.901934e-01
5   3.853456e+00  4.824943e+00 6.041349e+00  7.564421e+00 9.471471e+00
6   6.051287e+01 -1.199009e+02 2.375730e+02 -4.707297e+02 9.327092e+02
7   1.698811e-02 -8.613295e-03 4.367104e-03 -2.214204e-03 1.122644e-03
8   3.519469e-01  2.957263e-01 2.484865e-01  2.087929e-01 1.754400e-01
9   8.703874e-07 -8.504812e-08 8.310302e-09 -8.120241e-10 7.934526e-11
10  1.142475e-03  3.693925e-04 1.194343e-04  3.861627e-05 1.248566e-05
11  9.512045e+00 -1.384585e+01 2.015418e+01 -2.933667e+01 4.270281e+01
12  2.922203e-03  1.104915e-03 4.177795e-04  1.579667e-04 5.972882e-05
13  5.935231e+00  7.986268e+00 1.074608e+01  1.445960e+01 1.945641e+01
14  3.832242e-01  3.266092e-01 2.783581e-01  2.372353e-01 2.021877e-01
15  5.180885e+00  6.815085e+00 8.964759e+00  1.179250e+01 1.551220e+01
16  1.508321e-02  7.497376e-03 3.726704e-03  1.852424e-03 9.207805e-04
17  1.612464e+01  2.562939e+01 4.073677e+01  6.474927e+01 1.029161e+02
18  7.455666e+01  1.529564e+02 3.137969e+02  6.437684e+02 1.320720e+03
19  4.361154e-01  3.797825e-01 3.307261e-01  2.880064e-01 2.508047e-01
20  1.021678e+01 -1.504989e+01 2.216932e+01 -3.265663e+01 4.810502e+01
21  5.929662e-05  1.170941e-05 2.312278e-06  4.566095e-07 9.016748e-08
22  6.821042e+01  1.378772e+02 2.786983e+02  5.633471e+02 1.138722e+03
23  1.379677e-04 -3.136224e-05 7.129133e-06 -1.620564e-06 3.683799e-07
24  2.536063e-02  1.374633e-02 7.450980e-03  4.038686e-03 2.189106e-03
25  2.147732e-04  5.255855e-05 1.286195e-05  3.147531e-06 7.702530e-07
26  7.193824e-02 -4.639307e-02 2.991895e-02 -1.929477e-02 1.244323e-02
27  3.774250e-03 -1.489255e-03 5.876349e-04 -2.318708e-04 9.149228e-05
28  1.076393e-02 -5.057852e-03 2.376628e-03 -1.116751e-03 5.247490e-04
29  6.214232e-01 -5.740531e-01 5.302939e-01 -4.898704e-01 4.525284e-01
30  9.976039e-01 -9.972051e-01 9.968065e-01 -9.964080e-01 9.960097e-01
31  2.684302e-05 -4.644831e-06 8.037268e-07 -1.390743e-07 2.406498e-08
32  2.997812e-02 -1.670854e-02 9.312633e-03 -5.190468e-03 2.892948e-03
33  3.100298e-04 -8.065612e-05 2.098318e-05 -5.458900e-06 1.420166e-06
34  5.880537e-03 -2.498349e-03 1.061425e-03 -4.509469e-04 1.915850e-04
35  3.425386e-03  1.329927e-03 5.163523e-04  2.004769e-04 7.783638e-05
36  1.726394e+01  2.775428e+01 4.461902e+01  7.173151e+01 1.153188e+02
37  9.695988e-02 -6.571897e-02 4.454402e-02 -3.019174e-02 2.046382e-02
38  2.459286e-03 -9.035326e-04 3.319546e-04 -1.219589e-04 4.480725e-05
39  2.277322e+00  2.612132e+00 2.996166e+00  3.436660e+00 3.941916e+00
40  3.248003e-02 -1.834647e-02 1.036307e-02 -5.853621e-03 3.306440e-03
41  1.498032e-01 -1.091712e-01 7.956001e-02 -5.798046e-02 4.225407e-02
42  8.534200e-01  8.311702e-01 8.095004e-01  7.883957e-01 7.678411e-01
43  1.666930e+01 -2.664222e+01 4.258173e+01 -6.805753e+01 1.087750e+02
44  1.155266e+01 -1.736983e+01 2.611615e+01 -3.926655e+01 5.903865e+01
45  1.007378e-05  1.480441e-06 2.175654e-07  3.197338e-08 4.698803e-09
46  1.301729e-10  2.930494e-12 6.597219e-14  1.485187e-15 3.343499e-17
47  1.979739e+01  3.256186e+01 5.355630e+01  8.808702e+01 1.448816e+02
48  2.979286e+02  7.699532e+02 1.989832e+03  5.142430e+03 1.328986e+04
49  1.550624e-01 -1.136556e-01 8.330582e-02 -6.106042e-02 4.475527e-02
50  3.930669e-01 -3.364167e-01 2.879311e-01 -2.464335e-01 2.109166e-01
51  6.965925e+00 -9.626652e+00 1.330368e+01 -1.838519e+01 2.540766e+01
52  5.887334e-01 -5.389789e-01 4.934292e-01 -4.517290e-01 4.135529e-01
53  2.445150e+00  2.838070e+00 3.294129e+00  3.823475e+00 4.437883e+00
54  4.310596e-01  3.746510e-01 3.256240e-01  2.830127e-01 2.459776e-01
55  3.748899e+00  4.672554e+00 5.823780e+00  7.258646e+00 9.047034e+00
56  4.356492e-07  3.793089e-08 3.302549e-09  2.875447e-10 2.503580e-11
57  3.990080e-01  3.423565e-01 2.937484e-01  2.520417e-01 2.162566e-01
58  1.478848e+00  1.578498e+00 1.684863e+00  1.798396e+00 1.919578e+00
59  1.359572e+00 -1.430988e+00 1.506155e+00 -1.585271e+00 1.668542e+00
60  3.167986e-03 -1.214080e-03 4.652764e-04 -1.783097e-04 6.833430e-05
61  6.047034e-06  8.162055e-07 1.101683e-07  1.487009e-08 2.007108e-09
62  1.099481e-06  1.116998e-07 1.134794e-08  1.152874e-09 1.171241e-10
63  4.554747e-08 -2.721917e-09 1.626618e-10 -9.720673e-12 5.809076e-13
64  6.331634e-04 -1.855389e-04 5.436938e-05 -1.593212e-05 4.668668e-06
65  2.031743e-02 -1.061321e-02 5.544023e-03 -2.896030e-03 1.512799e-03
66  2.436298e-02  1.311754e-02 7.062752e-03  3.802732e-03 2.047470e-03
67  2.977352e-01  2.432961e-01 1.988109e-01  1.624596e-01 1.327548e-01
68  2.954047e-02 -1.642430e-02 9.131802e-03 -5.077221e-03 2.822901e-03
69  2.229340e+00  2.548036e+00 2.912292e+00  3.328621e+00 3.804466e+00
70  2.264153e-03 -8.204585e-04 2.973087e-04 -1.077354e-04 3.903997e-05
71  1.009879e-16 -2.179287e-19 4.702831e-22 -1.014856e-24 2.190026e-27
72  4.079137e-01  3.512877e-01 3.025225e-01  2.605268e-01 2.243609e-01
73  4.209821e+00 -5.349431e+00 6.797536e+00 -8.637647e+00 1.097588e+01
74  5.348671e+00 -7.073270e+00 9.353939e+00 -1.236998e+01 1.635849e+01
75  1.269808e-05 -1.939520e-06 2.962447e-07 -4.524878e-08 6.911355e-09
76  5.161990e+00  6.786096e+00 8.921191e+00  1.172805e+01 1.541802e+01
77  2.887499e-14  1.599345e-16 8.858545e-19  4.906623e-21 2.717709e-23
78  5.003619e-08  3.037374e-09 1.843794e-10  1.119248e-11 6.794232e-13
79  1.968587e+01 -3.234797e+01 5.315442e+01 -8.734375e+01 1.435239e+02
80  5.043170e+01  9.693654e+01 1.863251e+02  3.581421e+02 6.883975e+02
81  1.021943e+02  2.209689e+02 4.777883e+02  1.033094e+03 2.233801e+03
82  2.575287e+01  4.425509e+01 7.605028e+01  1.306888e+02 2.245825e+02
83  8.442632e-11  1.768306e-12 3.703711e-14  7.757410e-16 1.624787e-17
84  2.218802e-02 -1.176174e-02 6.234831e-03 -3.305048e-03 1.751987e-03
85  2.716156e+01 -4.709199e+01 8.164686e+01 -1.415572e+02 2.454282e+02
86  8.227829e+00  1.169049e+01 1.661041e+01  2.360086e+01 3.353323e+01
87  1.823753e-06  2.015860e-07 2.228203e-08  2.462913e-09 2.722347e-10
88  3.261717e-04  8.557640e-05 2.245235e-05  5.890734e-06 1.545529e-06
89  2.407647e+00  2.787350e+00 3.226936e+00  3.735848e+00 4.325018e+00
90  4.307102e-01 -3.742967e-01 3.252721e-01 -2.826687e-01 2.456454e-01
91  7.915047e+00 -1.117367e+01 1.577386e+01 -2.226795e+01 3.143565e+01
92  1.952956e-01 -1.487560e-01 1.133069e-01 -8.630552e-02 6.573863e-02
93  3.846673e+02 -1.037368e+03 2.797566e+03 -7.544456e+03 2.034583e+04
94  7.367093e+01 -1.508385e+02 3.088362e+02 -6.323307e+02 1.294674e+03
95  1.100684e+01  1.641622e+01 2.448406e+01  3.651690e+01 5.446335e+01
96  2.425216e-01 -1.915177e-01 1.512402e-01 -1.194334e-01 9.431573e-02
97  3.629100e-04  9.692418e-05 2.588602e-05  6.913508e-06 1.846425e-06
98  1.201327e+02 -2.668527e+02 5.927640e+02 -1.316716e+03 2.924841e+03
99  1.080271e-01  7.455126e-02 5.144902e-02  3.550580e-02 2.450312e-02
100 9.245748e-05 -1.966070e-05 4.180768e-06 -8.890232e-07 1.890471e-07
                y
1    -0.778502185
2    -2.386933026
3     2.911648114
4    -0.912773038
5     6.345960496
6    -7.396548115
7    -0.915371342
8     1.443043897
9     0.922882216
10   -0.584853974
11   -3.182083343
12    1.441777780
13    5.046027033
14    0.217399950
15    4.921102226
16    1.269310614
17    6.586009359
18   15.521320772
19    1.047115925
20   -1.414040073
21    1.376067299
22   14.127762458
23   -0.656101035
24    0.968701403
25   -0.601134312
26   -0.733494685
27   -2.717630855
28    1.303820053
29    0.282912413
30   -1.679025731
31   -0.483839819
32   -0.414008395
33   -1.150810465
34   -0.233303275
35   -0.153237003
36    9.657390938
37   -1.157212857
38   -1.337605876
39    5.136711742
40   -1.469503271
41   -0.294336234
42    3.186646628
43   -2.878475511
44   -0.816895292
45   -0.953560102
46    1.606815814
47   10.779082524
48   27.334767738
49    0.947507293
50    0.021872617
51   -1.051373987
52   -2.487209765
53    4.506265950
54    1.589128421
55    2.495243113
56    1.208518976
57    2.965191114
58    2.661864263
59   -0.569128848
60    0.130143316
61    1.691461436
62   -0.462245260
63   -1.791493238
64    1.125686447
65   -1.134010697
66    0.108430126
67    2.821240744
68   -1.275748804
69    4.112487273
70   -1.465986658
71    0.162764358
72    2.815809068
73   -2.549176603
74   -0.076441854
75    0.639782189
76    5.691687008
77   -0.004736039
78   -0.118460543
79   -4.519915270
80   13.155534639
81   17.841809120
82    8.391652198
83    0.340963176
84    0.286541532
85   -3.425634540
86    6.101626319
87   -1.074259064
88   -1.988996743
89    3.271774883
90    1.087452559
91   -2.668702219
92   -0.819327290
93  -14.475733692
94   -4.987730390
95    8.306411720
96   -1.568746402
97    0.333476546
98   -7.658947127
99    1.007449665
100   0.227224785</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>datos2 <span class="ot">&lt;-</span> datos</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(X, Y, type='p')</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>datos2<span class="sc">$</span><span class="st">'Y_ideal'</span> <span class="ot">&lt;-</span> <span class="fu">sapply</span>(X, <span class="cf">function</span>(x)(x<span class="sc">*</span>(<span class="dv">1</span> <span class="sc">+</span> x<span class="sc">*</span>(<span class="dv">1</span> <span class="sc">+</span> x))))</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datos2) <span class="sc">+</span> </span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>( <span class="fu">aes</span>(X1, Y), <span class="at">colour =</span> <span class="st">'black'</span> ) <span class="sc">+</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(X1, Y_ideal), <span class="at">colour =</span> <span class="st">'red'</span> ) </span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="selecciona-el-modelo-óptimo" class="level2">
<h2 class="anchored" data-anchor-id="selecciona-el-modelo-óptimo">Selecciona el modelo óptimo</h2>
<p>entre todos los submodelos que contienen como variabels regresoras <span class="math inline">\(X, X^2, X^3, \ldots, X^{10}\)</span>. ¿Cuál es el mejor modelo de acuerdo con los criterios <span class="math inline">\(C_p\)</span>, BIC y <span class="math inline">\(R_a^2\)</span>?</p>
<p><strong>Solución</strong> Para poder realizar estas comparaciones utilizaremos la función <img src="https://www.rdocumentation.org/packages/leaps/versions/3.1/topics/regsubsets.png" class="img-fluid" alt="leaps::regsubsets">.</p>
<p>Donde los argumentos que nos interesan son: - <code>datos</code> - <code>method</code> donde indicaremos de si se trata de <code>exhaustive</code> o <code>forward</code>.</p>
<p>Finalmente consultaremos los valores respectivos consultando los atributos de la salida:</p>
<ul>
<li><code>adjr2</code> para Adjusted r-squared.</li>
<li><code>cp</code> para Mallows’s CP.</li>
<li><code>bic</code> para Schwartz’s information criterion BIC.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>modelo_exhaustivo <span class="ot">&lt;-</span> leaps<span class="sc">::</span><span class="fu">regsubsets</span>(</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  y <span class="sc">~</span> ., </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data=</span>datos</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>resumen_1 <span class="ot">&lt;-</span> <span class="fu">summary</span>(modelo_exhaustivo)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>resumen_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Subset selection object
Call: regsubsets.formula(y ~ ., data = datos)
10 Variables  (and intercept)
     Forced in Forced out
X1       FALSE      FALSE
X1.1     FALSE      FALSE
X1.2     FALSE      FALSE
X1.3     FALSE      FALSE
X1.4     FALSE      FALSE
X1.5     FALSE      FALSE
X1.6     FALSE      FALSE
X1.7     FALSE      FALSE
X1.8     FALSE      FALSE
X1.9     FALSE      FALSE
1 subsets of each size up to 8
Selection Algorithm: exhaustive
         X1  X1.1 X1.2 X1.3 X1.4 X1.5 X1.6 X1.7 X1.8 X1.9
1  ( 1 ) " " " "  "*"  " "  " "  " "  " "  " "  " "  " " 
2  ( 1 ) " " "*"  "*"  " "  " "  " "  " "  " "  " "  " " 
3  ( 1 ) "*" "*"  "*"  " "  " "  " "  " "  " "  " "  " " 
4  ( 1 ) "*" "*"  "*"  " "  " "  " "  " "  " "  "*"  " " 
5  ( 1 ) "*" "*"  " "  " "  "*"  " "  "*"  " "  "*"  " " 
6  ( 1 ) "*" " "  "*"  "*"  " "  "*"  " "  "*"  " "  "*" 
7  ( 1 ) "*" " "  "*"  "*"  " "  "*"  " "  "*"  "*"  "*" 
8  ( 1 ) "*" " "  " "  "*"  "*"  "*"  "*"  "*"  "*"  "*" </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>pinta_ajuste <span class="ot">&lt;-</span> <span class="cf">function</span>(y_criterio, label){</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  plot_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> y_criterio</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(plot_data)</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  y_label <span class="ot">&lt;-</span> label</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>  ggp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(plot_data, <span class="fu">aes</span>(x, y)) <span class="sc">+</span>    <span class="co"># ggplot2 plot with default grid</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>()</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>  ggp <span class="sc">+</span> </span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"Número de variables"</span>) <span class="sc">+</span></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(y_label) <span class="co">#+</span></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>    <span class="co">#scale_y_continuous(minor_breaks = seq(0, 10, 0.005))</span></span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="mejor-modelo-de-acorde-a-r-cuadrado-ajustado" class="level3">
<h3 class="anchored" data-anchor-id="mejor-modelo-de-acorde-a-r-cuadrado-ajustado">Mejor modelo de acorde a R cuadrado ajustado</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pinta_ajuste</span>(resumen_1<span class="sc">$</span>adjr2, <span class="st">"R2 ajustado"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  x         y
1 1 0.8402396
2 2 0.9505834
3 3 0.9599265
4 4 0.9595260
5 5 0.9592342
6 6 0.9589036
7 7 0.9590800
8 8 0.9587991</code></pre>
</div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Se alcanza el máximo con "</span>, <span class="fu">which.max</span>(resumen_1<span class="sc">$</span>adjr2), <span class="st">"parametros"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Se alcanza el máximo con  3 parametros</code></pre>
</div>
</div>
<p>Será mejor donde alcance un máximo, esto es en <span class="math inline">\(p = 8\)</span> es decir utilizando 8 parámetros. Vamos a proceder a analizar los coeficientes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mejores elementos</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  X1  X1.1 X1.2 X1.3 X1.4 X1.5 X1.6 X1.7 X1.8 X1.9</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="co">#7  ( 1 ) " " "*"  "*"  " "  "*"  " "  "*"  "*"  "*"  "*" </span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>modelo_r2_a <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> X1<span class="fl">.1</span> <span class="sc">+</span> X1<span class="fl">.2</span><span class="sc">+</span> X1<span class="fl">.3</span>  <span class="sc">+</span> X1<span class="fl">.5</span> <span class="sc">+</span> X1<span class="fl">.6</span> <span class="sc">+</span> X1<span class="fl">.7</span> <span class="sc">+</span> X1<span class="fl">.8</span><span class="sc">+</span> X1<span class="fl">.9</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">data=</span>datos)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_r2_a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ X1.1 + X1.2 + X1.3 + X1.5 + X1.6 + X1.7 + X1.8 + 
    X1.9 - 1, data = datos)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.5417 -0.7535 -0.0185  0.7627  1.7039 

Coefficients:
      Estimate Std. Error t value Pr(&gt;|t|)    
X1.1 -0.947777   0.873024  -1.086   0.2805    
X1.2  1.573009   0.120752  13.027   &lt;2e-16 ***
X1.3  3.039759   1.391280   2.185   0.0314 *  
X1.5 -1.479865   0.729910  -2.027   0.0455 *  
X1.6 -0.027351   0.017728  -1.543   0.1263    
X1.7  0.282966   0.148767   1.902   0.0603 .  
X1.8  0.002332   0.002379   0.980   0.3295    
X1.9 -0.018219   0.010079  -1.808   0.0739 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.085 on 92 degrees of freedom
Multiple R-squared:  0.9621,    Adjusted R-squared:  0.9588 
F-statistic: 291.8 on 8 and 92 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>y_predit_r2_a <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="at">object=</span>modelo_r2_a, <span class="at">newdata=</span>datos)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>datos2<span class="sc">$</span><span class="st">'Y_r2a'</span> <span class="ot">&lt;-</span> y_predit_r2_a </span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datos2) <span class="sc">+</span> </span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>( <span class="fu">aes</span>(X1, Y), <span class="at">colour =</span> <span class="st">'black'</span> ) <span class="sc">+</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(X1, Y_ideal), <span class="at">colour =</span> <span class="st">'red'</span> ) <span class="sc">+</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(X1, Y_r2a), <span class="at">colour =</span> <span class="st">'green'</span> )</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Como vemos más variables lo que hacen es acercarse al ruido.</p>
</section>
<section id="cp" class="level3">
<h3 class="anchored" data-anchor-id="cp">Cp</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pinta_ajuste</span>(resumen_1<span class="sc">$</span>cp, <span class="st">"Cp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  x           y
1 1 276.1629460
2 2  19.9417035
3 3  -0.5535787
4 4   1.3982349
5 5   3.0880848
6 6   4.8499910
7 7   5.4872812
8 8   7.1223208</code></pre>
</div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Con el criterio CP, el mejor modelo tiene "</span>, <span class="fu">which.min</span>(resumen_1<span class="sc">$</span>cp), <span class="st">"parametros</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Con el criterio CP, el mejor modelo tiene  3 parametros</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_exhaustivo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Subset selection object
Call: regsubsets.formula(y ~ ., data = datos)
10 Variables  (and intercept)
     Forced in Forced out
X1       FALSE      FALSE
X1.1     FALSE      FALSE
X1.2     FALSE      FALSE
X1.3     FALSE      FALSE
X1.4     FALSE      FALSE
X1.5     FALSE      FALSE
X1.6     FALSE      FALSE
X1.7     FALSE      FALSE
X1.8     FALSE      FALSE
X1.9     FALSE      FALSE
1 subsets of each size up to 8
Selection Algorithm: exhaustive
         X1  X1.1 X1.2 X1.3 X1.4 X1.5 X1.6 X1.7 X1.8 X1.9
1  ( 1 ) " " " "  "*"  " "  " "  " "  " "  " "  " "  " " 
2  ( 1 ) " " "*"  "*"  " "  " "  " "  " "  " "  " "  " " 
3  ( 1 ) "*" "*"  "*"  " "  " "  " "  " "  " "  " "  " " 
4  ( 1 ) "*" "*"  "*"  " "  " "  " "  " "  " "  "*"  " " 
5  ( 1 ) "*" "*"  " "  " "  "*"  " "  "*"  " "  "*"  " " 
6  ( 1 ) "*" " "  "*"  "*"  " "  "*"  " "  "*"  " "  "*" 
7  ( 1 ) "*" " "  "*"  "*"  " "  "*"  " "  "*"  "*"  "*" 
8  ( 1 ) "*" " "  " "  "*"  "*"  "*"  "*"  "*"  "*"  "*" </code></pre>
</div>
</div>
<p>Vemos que con este criterio alcanza un mínimo en cinco variables. es decir que el mejor de los resultados sería</p>
<pre><code>Selection Algorithm: exhaustive
         X1  X1.1 X1.2 X1.3 X1.4 X1.5 X1.6 X1.7 X1.8 X1.9
6  ( 1 ) " " " "  "*"  "*"  "*"  "*"  " "  "*"  " "  "*" </code></pre>
<p>que si entrenamos obtendríamos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>modelo_cp<span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> X1<span class="fl">.2</span> <span class="sc">+</span> X1<span class="fl">.3</span> <span class="sc">+</span> X1<span class="fl">.4</span> <span class="sc">+</span> X1<span class="fl">.5</span> <span class="sc">+</span> X1<span class="fl">.7</span>  <span class="sc">+</span> X1<span class="fl">.9</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">data=</span>datos)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_cp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ X1.2 + X1.3 + X1.4 + X1.5 + X1.7 + X1.9 - 1, 
    data = datos)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.65825 -0.81003 -0.09833  0.70831  1.74356 

Coefficients:
     Estimate Std. Error t value Pr(&gt;|t|)    
X1.2  1.62365    0.09665  16.800  &lt; 2e-16 ***
X1.3  1.77301    0.37235   4.762 6.95e-06 ***
X1.4 -0.08244    0.02034  -4.054 0.000104 ***
X1.5 -0.92865    0.28881  -3.215 0.001786 ** 
X1.7  0.18720    0.06910   2.709 0.008013 ** 
X1.9 -0.01251    0.00507  -2.468 0.015411 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.08 on 94 degrees of freedom
Multiple R-squared:  0.9616,    Adjusted R-squared:  0.9592 
F-statistic: 392.4 on 6 and 94 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>X</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] -0.146150014 -0.685004253  1.103044432 -0.931186667  1.252107859
  [6] -1.981411263 -0.507018950  0.840258385 -0.097712944  0.323326386
 [11] -1.455612063  0.378110199  1.345569918  0.852266620  1.315428738
 [16]  0.497067779  1.589455303  2.051545132  0.870830367 -1.473055257
 [21]  0.197471759  2.021351255 -0.227315782  0.542034183  0.244716550
 [26] -0.644901366 -0.394583067 -0.469888874 -0.923771543 -0.999600253
 [31] -0.173036833 -0.557357770 -0.260156036 -0.424850525  0.388256077
 [36]  1.607644430 -0.677795496 -0.367396344  1.147019322 -0.564853818
 [41] -0.728763899  0.973928638 -1.598280163 -1.503535349  0.146959858
 [46]  0.022512313  1.644755410  2.584354249 -0.732966994 -0.855876444
 [51] -1.381963165 -0.915488955  1.160693583  0.869139636  1.246380431
 [56]  0.087067516  0.858019055  1.067383734 -1.052528149 -0.383233864
 [61]  0.134976161  0.101593199 -0.059760016 -0.293034867 -0.522369877
 [66]  0.538420700  0.817156102 -0.555993307  1.142955631 -0.362368926
 [71] -0.002157968  0.861181537 -1.270702655 -1.322434952 -0.152741242
 [76]  1.314627936  0.005538859  0.060703543 -1.643207561  1.922135184
 [81]  2.162242722  1.718452766  0.020944965 -0.530094243 -1.733773810
 [86]  1.420847749  0.110533608  0.262366097  1.157707358 -0.869022174
 [91] -1.411699465 -0.761696683 -2.696792601 -2.047462838  1.491455974
 [96] -0.789693231  0.267074955 -2.221315401  0.690116074 -0.212645899</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>y_predit_cp <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="at">object=</span>modelo_cp, <span class="at">newdata=</span>datos)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>datos2<span class="sc">$</span><span class="st">'Y_cp'</span> <span class="ot">&lt;-</span> y_predit_cp </span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datos2) <span class="sc">+</span> </span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>( <span class="fu">aes</span>(X1, Y), <span class="at">colour =</span> <span class="st">'black'</span> ) <span class="sc">+</span></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(X1, Y_ideal), <span class="at">colour =</span> <span class="st">'red'</span> ) <span class="sc">+</span></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(X1, Y_cp), <span class="at">colour =</span> <span class="st">'green'</span> )</span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="bic" class="level3">
<h3 class="anchored" data-anchor-id="bic">BIC</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pinta_ajuste</span>(resumen_1<span class="sc">$</span>bic, <span class="st">"Bic"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  x         y
1 1 -175.2129
2 2 -288.9722
3 3 -306.3604
4 4 -301.8079
5 5 -297.5427
6 6 -293.1993
7 7 -290.1054
8 8 -285.9089</code></pre>
</div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Con el criterio BIC, el mejor modelo tiene "</span>, <span class="fu">which.min</span>(resumen_1<span class="sc">$</span>bic), <span class="st">"parametros</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Con el criterio BIC, el mejor modelo tiene  3 parametros</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_exhaustivo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Subset selection object
Call: regsubsets.formula(y ~ ., data = datos)
10 Variables  (and intercept)
     Forced in Forced out
X1       FALSE      FALSE
X1.1     FALSE      FALSE
X1.2     FALSE      FALSE
X1.3     FALSE      FALSE
X1.4     FALSE      FALSE
X1.5     FALSE      FALSE
X1.6     FALSE      FALSE
X1.7     FALSE      FALSE
X1.8     FALSE      FALSE
X1.9     FALSE      FALSE
1 subsets of each size up to 8
Selection Algorithm: exhaustive
         X1  X1.1 X1.2 X1.3 X1.4 X1.5 X1.6 X1.7 X1.8 X1.9
1  ( 1 ) " " " "  "*"  " "  " "  " "  " "  " "  " "  " " 
2  ( 1 ) " " "*"  "*"  " "  " "  " "  " "  " "  " "  " " 
3  ( 1 ) "*" "*"  "*"  " "  " "  " "  " "  " "  " "  " " 
4  ( 1 ) "*" "*"  "*"  " "  " "  " "  " "  " "  "*"  " " 
5  ( 1 ) "*" "*"  " "  " "  "*"  " "  "*"  " "  "*"  " " 
6  ( 1 ) "*" " "  "*"  "*"  " "  "*"  " "  "*"  " "  "*" 
7  ( 1 ) "*" " "  "*"  "*"  " "  "*"  " "  "*"  "*"  "*" 
8  ( 1 ) "*" " "  " "  "*"  "*"  "*"  "*"  "*"  "*"  "*" </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>modelo_bic<span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> X1 <span class="sc">+</span> X1<span class="fl">.2</span> <span class="sc">+</span> X1<span class="fl">.3</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">data=</span>datos)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_bic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ X1 + X1.2 + X1.3 - 1, data = datos)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.6035 -0.4679  0.2761  1.2833  3.0855 

Coefficients:
     Estimate Std. Error t value Pr(&gt;|t|)    
X1    0.87378    0.22149   3.945 0.000151 ***
X1.2  1.06032    0.06221  17.045  &lt; 2e-16 ***
X1.3  0.21024    0.01499  14.030  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.316 on 97 degrees of freedom
Multiple R-squared:  0.9412,    Adjusted R-squared:  0.9394 
F-statistic: 517.7 on 3 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>y_predit_bic <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="at">object=</span>modelo_bic, <span class="at">newdata=</span>datos)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>datos2<span class="sc">$</span><span class="st">'Y_bic'</span> <span class="ot">&lt;-</span> y_predit_bic </span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datos2) <span class="sc">+</span> </span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>( <span class="fu">aes</span>(X1, Y), <span class="at">colour =</span> <span class="st">'black'</span> ) <span class="sc">+</span></span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(X1, Y_ideal), <span class="at">colour =</span> <span class="st">'red'</span> ) <span class="sc">+</span></span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(X1, Y_bic), <span class="at">colour =</span> <span class="st">'green'</span> )</span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="usando-ahora-el-método-iterativo" class="level2">
<h2 class="anchored" data-anchor-id="usando-ahora-el-método-iterativo">Usando ahora el método iterativo</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>modelo_iterativo_delante <span class="ot">&lt;-</span> leaps<span class="sc">::</span><span class="fu">regsubsets</span>(</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  y <span class="sc">~</span> ., </span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data=</span>datos, </span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"forward"</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>resumen_2 <span class="ot">&lt;-</span> <span class="fu">summary</span>(modelo_iterativo_delante)</span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>resumen_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Subset selection object
Call: regsubsets.formula(y ~ ., data = datos, method = "forward")
10 Variables  (and intercept)
     Forced in Forced out
X1       FALSE      FALSE
X1.1     FALSE      FALSE
X1.2     FALSE      FALSE
X1.3     FALSE      FALSE
X1.4     FALSE      FALSE
X1.5     FALSE      FALSE
X1.6     FALSE      FALSE
X1.7     FALSE      FALSE
X1.8     FALSE      FALSE
X1.9     FALSE      FALSE
1 subsets of each size up to 8
Selection Algorithm: forward
         X1  X1.1 X1.2 X1.3 X1.4 X1.5 X1.6 X1.7 X1.8 X1.9
1  ( 1 ) " " " "  "*"  " "  " "  " "  " "  " "  " "  " " 
2  ( 1 ) " " "*"  "*"  " "  " "  " "  " "  " "  " "  " " 
3  ( 1 ) "*" "*"  "*"  " "  " "  " "  " "  " "  " "  " " 
4  ( 1 ) "*" "*"  "*"  " "  " "  " "  " "  " "  "*"  " " 
5  ( 1 ) "*" "*"  "*"  "*"  " "  " "  " "  " "  "*"  " " 
6  ( 1 ) "*" "*"  "*"  "*"  "*"  " "  " "  " "  "*"  " " 
7  ( 1 ) "*" "*"  "*"  "*"  "*"  " "  "*"  " "  "*"  " " 
8  ( 1 ) "*" "*"  "*"  "*"  "*"  " "  "*"  " "  "*"  "*" </code></pre>
</div>
</div>
<p>Observaciones:</p>
<p>Como vemos ahora las variables seleccionadas para <span class="math inline">\(p\)</span> parámetros están incluídas en el modelo con <span class="math inline">\(p+1\)</span> parámetros. Esto es lo esperado ya que es el comportamiento de forward con el fin de mejorar el rendimiendo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>pinta_ajuste <span class="ot">&lt;-</span> <span class="cf">function</span>(y_criterio, label){</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>  plot_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>,</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> y_criterio</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(plot_data)</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>  y_label <span class="ot">&lt;-</span> label</span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb70-11"><a href="#cb70-11" aria-hidden="true" tabindex="-1"></a>  ggp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(plot_data, <span class="fu">aes</span>(x, y)) <span class="sc">+</span>    <span class="co"># ggplot2 plot with default grid</span></span>
<span id="cb70-12"><a href="#cb70-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>()</span>
<span id="cb70-13"><a href="#cb70-13" aria-hidden="true" tabindex="-1"></a>  ggp <span class="sc">+</span> </span>
<span id="cb70-14"><a href="#cb70-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"Número de variables"</span>) <span class="sc">+</span></span>
<span id="cb70-15"><a href="#cb70-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(y_label) <span class="co">#+</span></span>
<span id="cb70-16"><a href="#cb70-16" aria-hidden="true" tabindex="-1"></a>    <span class="co">#scale_y_continuous(minor_breaks = seq(0, 10, 0.005))</span></span>
<span id="cb70-17"><a href="#cb70-17" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="mejor-modelo-de-acorde-a-r-cuadrado-ajustado-con-modelo-iterativo-hacia-delante" class="level3">
<h3 class="anchored" data-anchor-id="mejor-modelo-de-acorde-a-r-cuadrado-ajustado-con-modelo-iterativo-hacia-delante">Mejor modelo de acorde a R cuadrado ajustado con modelo iterativo hacia delante</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pinta_ajuste</span>(resumen_2<span class="sc">$</span>adjr2, <span class="st">"R2 ajustado"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  x         y
1 1 0.8402396
2 2 0.9505834
3 3 0.9599265
4 4 0.9595260
5 5 0.9591119
6 6 0.9586908
7 7 0.9584058
8 8 0.9580191</code></pre>
</div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Se alcanza el máximo con "</span>, <span class="fu">which.max</span>(resumen_2<span class="sc">$</span>adjr2), <span class="st">"parametros"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Se alcanza el máximo con  3 parametros</code></pre>
</div>
</div>
<p>Será mejor donde alcance un máximo, esto es en <span class="math inline">\(p = 8\)</span> es decir utilizando 8 parámetros. Vamos a proceder a analizar los coeficientes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">#         X1  X1.1 X1.2 X1.3 X1.4 X1.5 X1.6 X1.7 X1.8 X1.9</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="co">#8  ( 1 ) "*" "*"  "*"  "*"  "*"  "*"  " "  "*"  " "  "*" </span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>modelo_r2_a <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> X1 <span class="sc">+</span> X1<span class="fl">.1</span> <span class="sc">+</span> X1<span class="fl">.2</span> <span class="sc">+</span> X1<span class="fl">.3</span> <span class="sc">+</span> X1<span class="fl">.4</span><span class="sc">+</span> X1<span class="fl">.5</span> <span class="sc">+</span> X1<span class="fl">.7</span> <span class="sc">+</span> X1<span class="fl">.9</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">data=</span>datos)</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_r2_a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ X1 + X1.1 + X1.2 + X1.3 + X1.4 + X1.5 + X1.7 + 
    X1.9 - 1, data = datos)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.3657 -0.7343 -0.0150  0.7812  1.9248 

Coefficients:
      Estimate Std. Error t value Pr(&gt;|t|)    
X1    0.644533   0.322280   2.000   0.0485 *  
X1.1 -0.457360   0.836749  -0.547   0.5860    
X1.2  1.234811   0.235429   5.245 9.94e-07 ***
X1.3  2.181665   1.276826   1.709   0.0909 .  
X1.4 -0.034997   0.036221  -0.966   0.3365    
X1.5 -1.027797   0.646555  -1.590   0.1153    
X1.7  0.192665   0.128532   1.499   0.1373    
X1.9 -0.012254   0.008555  -1.432   0.1554    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.059 on 92 degrees of freedom
Multiple R-squared:  0.9639,    Adjusted R-squared:  0.9607 
F-statistic: 306.9 on 8 and 92 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>y_predit_r2_a <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="at">object=</span>modelo_r2_a, <span class="at">newdata=</span>datos)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>datos2<span class="sc">$</span><span class="st">'Y_r2a'</span> <span class="ot">&lt;-</span> y_predit_r2_a </span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datos2) <span class="sc">+</span> </span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>( <span class="fu">aes</span>(X1, Y), <span class="at">colour =</span> <span class="st">'black'</span> ) <span class="sc">+</span></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(X1, Y_ideal), <span class="at">colour =</span> <span class="st">'red'</span> ) <span class="sc">+</span></span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(X1, Y_r2a), <span class="at">colour =</span> <span class="st">'green'</span> )</span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Como vemos más variables lo que hacen es acercarse al ruido.</p>
</section>
<section id="cp-1" class="level3">
<h3 class="anchored" data-anchor-id="cp-1">Cp</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pinta_ajuste</span>(resumen_2<span class="sc">$</span>cp, <span class="st">"Cp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  x           y
1 1 276.1629460
2 2  19.9417035
3 3  -0.5535787
4 4   1.3982349
5 5   3.3614505
6 6   5.3204040
7 7   6.9616861
8 8   8.8094113</code></pre>
</div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Con el criterio CP, el mejor modelo tiene "</span>, <span class="fu">which.min</span>(resumen_2<span class="sc">$</span>cp), <span class="st">"parametros</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Con el criterio CP, el mejor modelo tiene  3 parametros</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_iterativo_delante)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Subset selection object
Call: regsubsets.formula(y ~ ., data = datos, method = "forward")
10 Variables  (and intercept)
     Forced in Forced out
X1       FALSE      FALSE
X1.1     FALSE      FALSE
X1.2     FALSE      FALSE
X1.3     FALSE      FALSE
X1.4     FALSE      FALSE
X1.5     FALSE      FALSE
X1.6     FALSE      FALSE
X1.7     FALSE      FALSE
X1.8     FALSE      FALSE
X1.9     FALSE      FALSE
1 subsets of each size up to 8
Selection Algorithm: forward
         X1  X1.1 X1.2 X1.3 X1.4 X1.5 X1.6 X1.7 X1.8 X1.9
1  ( 1 ) " " " "  "*"  " "  " "  " "  " "  " "  " "  " " 
2  ( 1 ) " " "*"  "*"  " "  " "  " "  " "  " "  " "  " " 
3  ( 1 ) "*" "*"  "*"  " "  " "  " "  " "  " "  " "  " " 
4  ( 1 ) "*" "*"  "*"  " "  " "  " "  " "  " "  "*"  " " 
5  ( 1 ) "*" "*"  "*"  "*"  " "  " "  " "  " "  "*"  " " 
6  ( 1 ) "*" "*"  "*"  "*"  "*"  " "  " "  " "  "*"  " " 
7  ( 1 ) "*" "*"  "*"  "*"  "*"  " "  "*"  " "  "*"  " " 
8  ( 1 ) "*" "*"  "*"  "*"  "*"  " "  "*"  " "  "*"  "*" </code></pre>
</div>
</div>
<p>Vemos que con este criterio alcanza un mínimo en cinco variables. es decir que el mejor de los resultados sería</p>
<pre><code>Selection Algorithm: exhaustive
         X1  X1.1 X1.2 X1.3 X1.4 X1.5 X1.6 X1.7 X1.8 X1.9
6  ( 1 ) " " " "  "*"  "*"  "*"  "*"  " "  "*"  " "  "*" </code></pre>
<p>que si entrenamos obtendríamos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>modelo_cp<span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> X1<span class="fl">.2</span> <span class="sc">+</span> X1<span class="fl">.3</span> <span class="sc">+</span> X1<span class="fl">.4</span> <span class="sc">+</span> X1<span class="fl">.5</span> <span class="sc">+</span> X1<span class="fl">.7</span>  <span class="sc">+</span> X1<span class="fl">.9</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">data=</span>datos)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_cp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ X1.2 + X1.3 + X1.4 + X1.5 + X1.7 + X1.9 - 1, 
    data = datos)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.65825 -0.81003 -0.09833  0.70831  1.74356 

Coefficients:
     Estimate Std. Error t value Pr(&gt;|t|)    
X1.2  1.62365    0.09665  16.800  &lt; 2e-16 ***
X1.3  1.77301    0.37235   4.762 6.95e-06 ***
X1.4 -0.08244    0.02034  -4.054 0.000104 ***
X1.5 -0.92865    0.28881  -3.215 0.001786 ** 
X1.7  0.18720    0.06910   2.709 0.008013 ** 
X1.9 -0.01251    0.00507  -2.468 0.015411 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.08 on 94 degrees of freedom
Multiple R-squared:  0.9616,    Adjusted R-squared:  0.9592 
F-statistic: 392.4 on 6 and 94 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>X</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] -0.146150014 -0.685004253  1.103044432 -0.931186667  1.252107859
  [6] -1.981411263 -0.507018950  0.840258385 -0.097712944  0.323326386
 [11] -1.455612063  0.378110199  1.345569918  0.852266620  1.315428738
 [16]  0.497067779  1.589455303  2.051545132  0.870830367 -1.473055257
 [21]  0.197471759  2.021351255 -0.227315782  0.542034183  0.244716550
 [26] -0.644901366 -0.394583067 -0.469888874 -0.923771543 -0.999600253
 [31] -0.173036833 -0.557357770 -0.260156036 -0.424850525  0.388256077
 [36]  1.607644430 -0.677795496 -0.367396344  1.147019322 -0.564853818
 [41] -0.728763899  0.973928638 -1.598280163 -1.503535349  0.146959858
 [46]  0.022512313  1.644755410  2.584354249 -0.732966994 -0.855876444
 [51] -1.381963165 -0.915488955  1.160693583  0.869139636  1.246380431
 [56]  0.087067516  0.858019055  1.067383734 -1.052528149 -0.383233864
 [61]  0.134976161  0.101593199 -0.059760016 -0.293034867 -0.522369877
 [66]  0.538420700  0.817156102 -0.555993307  1.142955631 -0.362368926
 [71] -0.002157968  0.861181537 -1.270702655 -1.322434952 -0.152741242
 [76]  1.314627936  0.005538859  0.060703543 -1.643207561  1.922135184
 [81]  2.162242722  1.718452766  0.020944965 -0.530094243 -1.733773810
 [86]  1.420847749  0.110533608  0.262366097  1.157707358 -0.869022174
 [91] -1.411699465 -0.761696683 -2.696792601 -2.047462838  1.491455974
 [96] -0.789693231  0.267074955 -2.221315401  0.690116074 -0.212645899</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>y_predit_cp <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="at">object=</span>modelo_cp, <span class="at">newdata=</span>datos)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>datos2<span class="sc">$</span><span class="st">'Y_cp'</span> <span class="ot">&lt;-</span> y_predit_cp </span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datos2) <span class="sc">+</span> </span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>( <span class="fu">aes</span>(X1, Y), <span class="at">colour =</span> <span class="st">'black'</span> ) <span class="sc">+</span></span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(X1, Y_ideal), <span class="at">colour =</span> <span class="st">'red'</span> ) <span class="sc">+</span></span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(X1, Y_cp), <span class="at">colour =</span> <span class="st">'green'</span> )</span>
<span id="cb89-9"><a href="#cb89-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb89-10"><a href="#cb89-10" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="bic-1" class="level3">
<h3 class="anchored" data-anchor-id="bic-1">BIC</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pinta_ajuste</span>(resumen_2<span class="sc">$</span>bic, <span class="st">"Bic"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  x         y
1 1 -175.2129
2 2 -288.9722
3 3 -306.3604
4 4 -301.8079
5 5 -297.2430
6 6 -292.6828
7 7 -288.4712
8 8 -284.0336</code></pre>
</div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Con el criterio BIC, el mejor modelo tiene "</span>, <span class="fu">which.min</span>(resumen_1<span class="sc">$</span>bic), <span class="st">"parametros</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Con el criterio BIC, el mejor modelo tiene  3 parametros</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_iterativo_delante)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Subset selection object
Call: regsubsets.formula(y ~ ., data = datos, method = "forward")
10 Variables  (and intercept)
     Forced in Forced out
X1       FALSE      FALSE
X1.1     FALSE      FALSE
X1.2     FALSE      FALSE
X1.3     FALSE      FALSE
X1.4     FALSE      FALSE
X1.5     FALSE      FALSE
X1.6     FALSE      FALSE
X1.7     FALSE      FALSE
X1.8     FALSE      FALSE
X1.9     FALSE      FALSE
1 subsets of each size up to 8
Selection Algorithm: forward
         X1  X1.1 X1.2 X1.3 X1.4 X1.5 X1.6 X1.7 X1.8 X1.9
1  ( 1 ) " " " "  "*"  " "  " "  " "  " "  " "  " "  " " 
2  ( 1 ) " " "*"  "*"  " "  " "  " "  " "  " "  " "  " " 
3  ( 1 ) "*" "*"  "*"  " "  " "  " "  " "  " "  " "  " " 
4  ( 1 ) "*" "*"  "*"  " "  " "  " "  " "  " "  "*"  " " 
5  ( 1 ) "*" "*"  "*"  "*"  " "  " "  " "  " "  "*"  " " 
6  ( 1 ) "*" "*"  "*"  "*"  "*"  " "  " "  " "  "*"  " " 
7  ( 1 ) "*" "*"  "*"  "*"  "*"  " "  "*"  " "  "*"  " " 
8  ( 1 ) "*" "*"  "*"  "*"  "*"  " "  "*"  " "  "*"  "*" </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>modelo_bic<span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> X1 <span class="sc">+</span> X1<span class="fl">.1</span> <span class="sc">+</span>  X1<span class="fl">.2</span>  <span class="sc">-</span><span class="dv">1</span>, <span class="at">data=</span>datos)</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_bic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ X1 + X1.1 + X1.2 - 1, data = datos)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.47734 -0.83784 -0.05139  0.61421  1.85231 

Coefficients:
     Estimate Std. Error t value Pr(&gt;|t|)    
X1    0.87231    0.17682   4.933 3.35e-06 ***
X1.1  1.07413    0.05634  19.066  &lt; 2e-16 ***
X1.2  1.03076    0.04952  20.814  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.051 on 97 degrees of freedom
Multiple R-squared:  0.9625,    Adjusted R-squared:  0.9613 
F-statistic: 829.7 on 3 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>y_predit_bic <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="at">object=</span>modelo_bic, <span class="at">newdata=</span>datos)</span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>datos2<span class="sc">$</span><span class="st">'Y_bic'</span> <span class="ot">&lt;-</span> y_predit_bic </span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datos2) <span class="sc">+</span> </span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>( <span class="fu">aes</span>(X1, Y), <span class="at">colour =</span> <span class="st">'black'</span> ) <span class="sc">+</span></span>
<span id="cb98-7"><a href="#cb98-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(X1, Y_ideal), <span class="at">colour =</span> <span class="st">'red'</span> ) <span class="sc">+</span></span>
<span id="cb98-8"><a href="#cb98-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(X1, Y_bic), <span class="at">colour =</span> <span class="st">'green'</span> )</span>
<span id="cb98-9"><a href="#cb98-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb98-10"><a href="#cb98-10" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">'Los coefficientes del modelo son'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Los coefficientes del modelo son"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(modelo_bic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       X1      X1.1      X1.2 
0.8723145 1.0741292 1.0307556 </code></pre>
</div>
</div>
</section>
</section>
<section id="lasso" class="level2">
<h2 class="anchored" data-anchor-id="lasso">Lasso</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'Matrix'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:ramify':

    tril, triu</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loaded glmnet 4.1-6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> datos[<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)]</span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              X1         X1.1          X1.2         X1.3          X1.4
1   -0.146150014 2.135983e-02 -3.121739e-03 4.562422e-04 -6.667980e-05
2   -0.685004253 4.692308e-01 -3.214251e-01 2.201776e-01 -1.508226e-01
3    1.103044432 1.216707e+00  1.342082e+00 1.480376e+00  1.632920e+00
4   -0.931186667 8.671086e-01 -8.074400e-01 7.518773e-01 -7.001382e-01
5    1.252107859 1.567774e+00  1.963022e+00 2.457916e+00  3.077575e+00
6   -1.981411263 3.925991e+00 -7.779002e+00 1.541340e+01 -3.054029e+01
7   -0.507018950 2.570682e-01 -1.303385e-01 6.608407e-02 -3.350587e-02
8    0.840258385 7.060342e-01  5.932511e-01 4.984842e-01  4.188555e-01
9   -0.097712944 9.547820e-03 -9.329456e-04 9.116086e-05 -8.907596e-06
10   0.323326386 1.045400e-01  3.380052e-02 1.092860e-02  3.533505e-03
11  -1.455612063 2.118806e+00 -3.084160e+00 4.489341e+00 -6.534739e+00
12   0.378110199 1.429673e-01  5.405740e-02 2.043966e-02  7.728442e-03
13   1.345569918 1.810558e+00  2.436233e+00 3.278122e+00  4.410942e+00
14   0.852266620 7.263584e-01  6.190510e-01 5.275965e-01  4.496529e-01
15   1.315428738 1.730353e+00  2.276156e+00 2.994121e+00  3.938552e+00
16   0.497067779 2.470764e-01  1.228137e-01 6.104674e-02  3.034437e-02
17   1.589455303 2.526368e+00  4.015549e+00 6.382536e+00  1.014476e+01
18   2.051545132 4.208837e+00  8.634620e+00 1.771431e+01  3.634171e+01
19   0.870830367 7.583455e-01  6.603903e-01 5.750879e-01  5.008040e-01
20  -1.473055257 2.169892e+00 -3.196371e+00 4.708430e+00 -6.935778e+00
21   0.197471759 3.899510e-02  7.700430e-03 1.520617e-03  3.002790e-04
22   2.021351255 4.085861e+00  8.258960e+00 1.669426e+01  3.374496e+01
23  -0.227315782 5.167246e-02 -1.174597e-02 2.670044e-03 -6.069431e-04
24   0.542034183 2.938011e-01  1.592502e-01 8.631906e-02  4.678788e-02
25   0.244716550 5.988619e-02  1.465514e-02 3.586356e-03  8.776406e-04
26  -0.644901366 4.158978e-01 -2.682130e-01 1.729710e-01 -1.115492e-01
27  -0.394583067 1.556958e-01 -6.143493e-02 2.424118e-02 -9.565160e-03
28  -0.469888874 2.207956e-01 -1.037494e-01 4.875068e-02 -2.290740e-02
29  -0.923771543 8.533539e-01 -7.883040e-01 7.282128e-01 -6.727023e-01
30  -0.999600253 9.992007e-01 -9.988012e-01 9.984020e-01 -9.980029e-01
31  -0.173036833 2.994175e-02 -5.181025e-03 8.965081e-04 -1.551289e-04
32  -0.557357770 3.106477e-01 -1.731419e-01 9.650198e-02 -5.378613e-02
33  -0.260156036 6.768116e-02 -1.760766e-02 4.580740e-03 -1.191707e-03
34  -0.424850525 1.804980e-01 -7.668466e-02 3.257952e-02 -1.384142e-02
35   0.388256077 1.507428e-01  5.852680e-02 2.272339e-02  8.822493e-03
36   1.607644430 2.584521e+00  4.154990e+00 6.679747e+00  1.073866e+01
37  -0.677795496 4.594067e-01 -3.113838e-01 2.110545e-01 -1.430518e-01
38  -0.367396344 1.349801e-01 -4.959119e-02 1.821962e-02 -6.693822e-03
39   1.147019322 1.315653e+00  1.509080e+00 1.730944e+00  1.985426e+00
40  -0.564853818 3.190598e-01 -1.802222e-01 1.017992e-01 -5.750165e-02
41  -0.728763899 5.310968e-01 -3.870442e-01 2.820638e-01 -2.055579e-01
42   0.973928638 9.485370e-01  9.238073e-01 8.997224e-01  8.762654e-01
43  -1.598280163 2.554499e+00 -4.082806e+00 6.525468e+00 -1.042953e+01
44  -1.503535349 2.260619e+00 -3.398920e+00 5.110396e+00 -7.683661e+00
45   0.146959858 2.159720e-02  3.173921e-03 4.664390e-04  6.854782e-05
46   0.022512313 5.068042e-04  1.140934e-05 2.568505e-07  5.782299e-09
47   1.644755410 2.705220e+00  4.449426e+00 7.318217e+00  1.203668e+01
48   2.584354249 6.678887e+00  1.726061e+01 4.460753e+01  1.152817e+02
49  -0.732966994 5.372406e-01 -3.937796e-01 2.886275e-01 -2.115544e-01
50  -0.855876444 7.325245e-01 -6.269505e-01 5.365921e-01 -4.592566e-01
51  -1.381963165 1.909822e+00 -2.639304e+00 3.647421e+00 -5.040601e+00
52  -0.915488955 8.381200e-01 -7.672896e-01 7.024452e-01 -6.430808e-01
53   1.160693583 1.347210e+00  1.563698e+00 1.814974e+00  2.106628e+00
54   0.869139636 7.554037e-01  6.565513e-01 5.706348e-01  4.959613e-01
55   1.246380431 1.553464e+00  1.936207e+00 2.413251e+00  3.007829e+00
56   0.087067516 7.580752e-03  6.600373e-04 5.746781e-05  5.003579e-06
57   0.858019055 7.361967e-01  6.316708e-01 5.419856e-01  4.650340e-01
58   1.067383734 1.139308e+00  1.216079e+00 1.298023e+00  1.385488e+00
59  -1.052528149 1.107816e+00 -1.166007e+00 1.227255e+00 -1.291721e+00
60  -0.383233864 1.468682e-01 -5.628487e-02 2.157027e-02 -8.266457e-03
61   0.134976161 1.821856e-02  2.459072e-03 3.319161e-04  4.480076e-05
62   0.101593199 1.032118e-02  1.048562e-03 1.065267e-04  1.082239e-05
63  -0.059760016 3.571259e-03 -2.134185e-04 1.275389e-05 -7.621729e-07
64  -0.293034867 8.586943e-02 -2.516274e-02 7.373560e-03 -2.160710e-03
65  -0.522369877 2.728703e-01 -1.425392e-01 7.445819e-02 -3.889472e-02
66   0.538420700 2.898969e-01  1.560865e-01 8.404018e-02  4.524897e-02
67   0.817156102 6.677441e-01  5.456512e-01 4.458822e-01  3.643553e-01
68  -0.555993307 3.091286e-01 -1.718734e-01 9.556047e-02 -5.313098e-02
69   1.142955631 1.306348e+00  1.493097e+00 1.706544e+00  1.950504e+00
70  -0.362368926 1.313112e-01 -4.758311e-02 1.724264e-02 -6.248197e-03
71  -0.002157968 4.656824e-06 -1.004928e-08 2.168601e-11 -4.679771e-14
72   0.861181537 7.416336e-01  6.386812e-01 5.500205e-01  4.736675e-01
73  -1.270702655 1.614685e+00 -2.051785e+00 2.607208e+00 -3.312987e+00
74  -1.322434952 1.748834e+00 -2.312719e+00 3.058421e+00 -4.044563e+00
75  -0.152741242 2.332989e-02 -3.563436e-03 5.442836e-04 -8.313456e-05
76   1.314627936 1.728247e+00  2.272001e+00 2.986836e+00  3.926579e+00
77   0.005538859 3.067896e-05  1.699264e-07 9.411984e-10  5.213165e-12
78   0.060703543 3.684920e-03  2.236877e-04 1.357864e-05  8.242713e-07
79  -1.643207561 2.700131e+00 -4.436876e+00 7.290708e+00 -1.198015e+01
80   1.922135184 3.694604e+00  7.101528e+00 1.365010e+01  2.623733e+01
81   2.162242722 4.675294e+00  1.010912e+01 2.185837e+01  4.726310e+01
82   1.718452766 2.953080e+00  5.074728e+00 8.720681e+00  1.498608e+01
83   0.020944965 4.386916e-04  9.188379e-06 1.924503e-07  4.030865e-09
84  -0.530094243 2.809999e-01 -1.489564e-01 7.896095e-02 -4.185674e-02
85  -1.733773810 3.005972e+00 -5.211675e+00 9.035865e+00 -1.566615e+01
86   1.420847749 2.018808e+00  2.868419e+00 4.075587e+00  5.790789e+00
87   0.110533608 1.221768e-02  1.350464e-03 1.492717e-04  1.649954e-05
88   0.262366097 6.883597e-02  1.806022e-02 4.738391e-03  1.243193e-03
89   1.157707358 1.340286e+00  1.551659e+00 1.796367e+00  2.079668e+00
90  -0.869022174 7.551995e-01 -6.562851e-01 5.703263e-01 -4.956262e-01
91  -1.411699465 1.992895e+00 -2.813369e+00 3.971632e+00 -5.606751e+00
92  -0.761696683 5.801818e-01 -4.419226e-01 3.366110e-01 -2.563955e-01
93  -2.696792601 7.272690e+00 -1.961294e+01 5.289202e+01 -1.426388e+02
94  -2.047462838 4.192104e+00 -8.583177e+00 1.757374e+01 -3.598157e+01
95   1.491455974 2.224441e+00  3.317656e+00 4.948137e+00  7.379929e+00
96  -0.789693231 6.236154e-01 -4.924649e-01 3.888962e-01 -3.071087e-01
97   0.267074955 7.132903e-02  1.905020e-02 5.087831e-03  1.358832e-03
98  -2.221315401 4.934242e+00 -1.096051e+01 2.434675e+01 -5.408180e+01
99   0.690116074 4.762602e-01  3.286748e-01 2.268238e-01  1.565347e-01
100 -0.212645899 4.521828e-02 -9.615481e-03 2.044693e-03 -4.347955e-04
            X1.5          X1.6         X1.7          X1.8         X1.9
1   9.745254e-06 -1.424269e-06 2.081569e-07 -3.042214e-08 4.446196e-09
2   1.033141e-01 -7.077060e-02 4.847816e-02 -3.320775e-02 2.274745e-02
3   1.801184e+00  1.986786e+00 2.191513e+00  2.417336e+00 2.666429e+00
4   6.519593e-01 -6.070958e-01 5.653195e-01 -5.264180e-01 4.901934e-01
5   3.853456e+00  4.824943e+00 6.041349e+00  7.564421e+00 9.471471e+00
6   6.051287e+01 -1.199009e+02 2.375730e+02 -4.707297e+02 9.327092e+02
7   1.698811e-02 -8.613295e-03 4.367104e-03 -2.214204e-03 1.122644e-03
8   3.519469e-01  2.957263e-01 2.484865e-01  2.087929e-01 1.754400e-01
9   8.703874e-07 -8.504812e-08 8.310302e-09 -8.120241e-10 7.934526e-11
10  1.142475e-03  3.693925e-04 1.194343e-04  3.861627e-05 1.248566e-05
11  9.512045e+00 -1.384585e+01 2.015418e+01 -2.933667e+01 4.270281e+01
12  2.922203e-03  1.104915e-03 4.177795e-04  1.579667e-04 5.972882e-05
13  5.935231e+00  7.986268e+00 1.074608e+01  1.445960e+01 1.945641e+01
14  3.832242e-01  3.266092e-01 2.783581e-01  2.372353e-01 2.021877e-01
15  5.180885e+00  6.815085e+00 8.964759e+00  1.179250e+01 1.551220e+01
16  1.508321e-02  7.497376e-03 3.726704e-03  1.852424e-03 9.207805e-04
17  1.612464e+01  2.562939e+01 4.073677e+01  6.474927e+01 1.029161e+02
18  7.455666e+01  1.529564e+02 3.137969e+02  6.437684e+02 1.320720e+03
19  4.361154e-01  3.797825e-01 3.307261e-01  2.880064e-01 2.508047e-01
20  1.021678e+01 -1.504989e+01 2.216932e+01 -3.265663e+01 4.810502e+01
21  5.929662e-05  1.170941e-05 2.312278e-06  4.566095e-07 9.016748e-08
22  6.821042e+01  1.378772e+02 2.786983e+02  5.633471e+02 1.138722e+03
23  1.379677e-04 -3.136224e-05 7.129133e-06 -1.620564e-06 3.683799e-07
24  2.536063e-02  1.374633e-02 7.450980e-03  4.038686e-03 2.189106e-03
25  2.147732e-04  5.255855e-05 1.286195e-05  3.147531e-06 7.702530e-07
26  7.193824e-02 -4.639307e-02 2.991895e-02 -1.929477e-02 1.244323e-02
27  3.774250e-03 -1.489255e-03 5.876349e-04 -2.318708e-04 9.149228e-05
28  1.076393e-02 -5.057852e-03 2.376628e-03 -1.116751e-03 5.247490e-04
29  6.214232e-01 -5.740531e-01 5.302939e-01 -4.898704e-01 4.525284e-01
30  9.976039e-01 -9.972051e-01 9.968065e-01 -9.964080e-01 9.960097e-01
31  2.684302e-05 -4.644831e-06 8.037268e-07 -1.390743e-07 2.406498e-08
32  2.997812e-02 -1.670854e-02 9.312633e-03 -5.190468e-03 2.892948e-03
33  3.100298e-04 -8.065612e-05 2.098318e-05 -5.458900e-06 1.420166e-06
34  5.880537e-03 -2.498349e-03 1.061425e-03 -4.509469e-04 1.915850e-04
35  3.425386e-03  1.329927e-03 5.163523e-04  2.004769e-04 7.783638e-05
36  1.726394e+01  2.775428e+01 4.461902e+01  7.173151e+01 1.153188e+02
37  9.695988e-02 -6.571897e-02 4.454402e-02 -3.019174e-02 2.046382e-02
38  2.459286e-03 -9.035326e-04 3.319546e-04 -1.219589e-04 4.480725e-05
39  2.277322e+00  2.612132e+00 2.996166e+00  3.436660e+00 3.941916e+00
40  3.248003e-02 -1.834647e-02 1.036307e-02 -5.853621e-03 3.306440e-03
41  1.498032e-01 -1.091712e-01 7.956001e-02 -5.798046e-02 4.225407e-02
42  8.534200e-01  8.311702e-01 8.095004e-01  7.883957e-01 7.678411e-01
43  1.666930e+01 -2.664222e+01 4.258173e+01 -6.805753e+01 1.087750e+02
44  1.155266e+01 -1.736983e+01 2.611615e+01 -3.926655e+01 5.903865e+01
45  1.007378e-05  1.480441e-06 2.175654e-07  3.197338e-08 4.698803e-09
46  1.301729e-10  2.930494e-12 6.597219e-14  1.485187e-15 3.343499e-17
47  1.979739e+01  3.256186e+01 5.355630e+01  8.808702e+01 1.448816e+02
48  2.979286e+02  7.699532e+02 1.989832e+03  5.142430e+03 1.328986e+04
49  1.550624e-01 -1.136556e-01 8.330582e-02 -6.106042e-02 4.475527e-02
50  3.930669e-01 -3.364167e-01 2.879311e-01 -2.464335e-01 2.109166e-01
51  6.965925e+00 -9.626652e+00 1.330368e+01 -1.838519e+01 2.540766e+01
52  5.887334e-01 -5.389789e-01 4.934292e-01 -4.517290e-01 4.135529e-01
53  2.445150e+00  2.838070e+00 3.294129e+00  3.823475e+00 4.437883e+00
54  4.310596e-01  3.746510e-01 3.256240e-01  2.830127e-01 2.459776e-01
55  3.748899e+00  4.672554e+00 5.823780e+00  7.258646e+00 9.047034e+00
56  4.356492e-07  3.793089e-08 3.302549e-09  2.875447e-10 2.503580e-11
57  3.990080e-01  3.423565e-01 2.937484e-01  2.520417e-01 2.162566e-01
58  1.478848e+00  1.578498e+00 1.684863e+00  1.798396e+00 1.919578e+00
59  1.359572e+00 -1.430988e+00 1.506155e+00 -1.585271e+00 1.668542e+00
60  3.167986e-03 -1.214080e-03 4.652764e-04 -1.783097e-04 6.833430e-05
61  6.047034e-06  8.162055e-07 1.101683e-07  1.487009e-08 2.007108e-09
62  1.099481e-06  1.116998e-07 1.134794e-08  1.152874e-09 1.171241e-10
63  4.554747e-08 -2.721917e-09 1.626618e-10 -9.720673e-12 5.809076e-13
64  6.331634e-04 -1.855389e-04 5.436938e-05 -1.593212e-05 4.668668e-06
65  2.031743e-02 -1.061321e-02 5.544023e-03 -2.896030e-03 1.512799e-03
66  2.436298e-02  1.311754e-02 7.062752e-03  3.802732e-03 2.047470e-03
67  2.977352e-01  2.432961e-01 1.988109e-01  1.624596e-01 1.327548e-01
68  2.954047e-02 -1.642430e-02 9.131802e-03 -5.077221e-03 2.822901e-03
69  2.229340e+00  2.548036e+00 2.912292e+00  3.328621e+00 3.804466e+00
70  2.264153e-03 -8.204585e-04 2.973087e-04 -1.077354e-04 3.903997e-05
71  1.009879e-16 -2.179287e-19 4.702831e-22 -1.014856e-24 2.190026e-27
72  4.079137e-01  3.512877e-01 3.025225e-01  2.605268e-01 2.243609e-01
73  4.209821e+00 -5.349431e+00 6.797536e+00 -8.637647e+00 1.097588e+01
74  5.348671e+00 -7.073270e+00 9.353939e+00 -1.236998e+01 1.635849e+01
75  1.269808e-05 -1.939520e-06 2.962447e-07 -4.524878e-08 6.911355e-09
76  5.161990e+00  6.786096e+00 8.921191e+00  1.172805e+01 1.541802e+01
77  2.887499e-14  1.599345e-16 8.858545e-19  4.906623e-21 2.717709e-23
78  5.003619e-08  3.037374e-09 1.843794e-10  1.119248e-11 6.794232e-13
79  1.968587e+01 -3.234797e+01 5.315442e+01 -8.734375e+01 1.435239e+02
80  5.043170e+01  9.693654e+01 1.863251e+02  3.581421e+02 6.883975e+02
81  1.021943e+02  2.209689e+02 4.777883e+02  1.033094e+03 2.233801e+03
82  2.575287e+01  4.425509e+01 7.605028e+01  1.306888e+02 2.245825e+02
83  8.442632e-11  1.768306e-12 3.703711e-14  7.757410e-16 1.624787e-17
84  2.218802e-02 -1.176174e-02 6.234831e-03 -3.305048e-03 1.751987e-03
85  2.716156e+01 -4.709199e+01 8.164686e+01 -1.415572e+02 2.454282e+02
86  8.227829e+00  1.169049e+01 1.661041e+01  2.360086e+01 3.353323e+01
87  1.823753e-06  2.015860e-07 2.228203e-08  2.462913e-09 2.722347e-10
88  3.261717e-04  8.557640e-05 2.245235e-05  5.890734e-06 1.545529e-06
89  2.407647e+00  2.787350e+00 3.226936e+00  3.735848e+00 4.325018e+00
90  4.307102e-01 -3.742967e-01 3.252721e-01 -2.826687e-01 2.456454e-01
91  7.915047e+00 -1.117367e+01 1.577386e+01 -2.226795e+01 3.143565e+01
92  1.952956e-01 -1.487560e-01 1.133069e-01 -8.630552e-02 6.573863e-02
93  3.846673e+02 -1.037368e+03 2.797566e+03 -7.544456e+03 2.034583e+04
94  7.367093e+01 -1.508385e+02 3.088362e+02 -6.323307e+02 1.294674e+03
95  1.100684e+01  1.641622e+01 2.448406e+01  3.651690e+01 5.446335e+01
96  2.425216e-01 -1.915177e-01 1.512402e-01 -1.194334e-01 9.431573e-02
97  3.629100e-04  9.692418e-05 2.588602e-05  6.913508e-06 1.846425e-06
98  1.201327e+02 -2.668527e+02 5.927640e+02 -1.316716e+03 2.924841e+03
99  1.080271e-01  7.455126e-02 5.144902e-02  3.550580e-02 2.450312e-02
100 9.245748e-05 -1.966070e-05 4.180768e-06 -8.890232e-07 1.890471e-07</code></pre>
</div>
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> datos<span class="sc">$</span>y</span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>modelo_lasso <span class="ot">&lt;-</span> <span class="fu">glmnet</span>(x, y, <span class="at">alpha =</span> <span class="dv">1</span>, <span class="at">intercept=</span><span class="cn">FALSE</span>)   <span class="co"># alpha = 1 (lasso); alpha = 0 (ridge)</span></span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo_lasso, <span class="at">xvar=</span><span class="st">'lambda'</span>, <span class="at">label=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(modelo_lasso, <span class="at">s =</span> <span class="fl">0.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>11 x 1 sparse Matrix of class "dgCMatrix"
                     s1
(Intercept) .          
X1          0.834112004
X1.1        1.029551213
X1.2        1.014180377
X1.3        0.001199474
X1.4        .          
X1.5        .          
X1.6        .          
X1.7        .          
X1.8        .          
X1.9        .          </code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="co">#help(coef)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>La ventaja que tiene lasso es que permite eliminar ciertos coeficientes esto queda de manifiesto en que la mayoría son nulos.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="ejercicio-12" class="level1">
<h1>Ejercicio 12</h1>
<p>Se generan los siguientes dos conjuntos de datos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr)</span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>sigma_1 <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a>sigma_2 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-5"><a href="#cb115-5" aria-hidden="true" tabindex="-1"></a>fun_reg <span class="ot">&lt;-</span> <span class="cf">function</span> (x) (x<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span><span class="fu">sin</span>(x))</span>
<span id="cb115-6"><a href="#cb115-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-7"><a href="#cb115-7" aria-hidden="true" tabindex="-1"></a>generator <span class="ot">&lt;-</span> <span class="cf">function</span> (n, sigma) {</span>
<span id="cb115-8"><a href="#cb115-8" aria-hidden="true" tabindex="-1"></a>  error <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb115-9"><a href="#cb115-9" aria-hidden="true" tabindex="-1"></a>  unif <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="at">min =</span> <span class="sc">-</span>pi, <span class="at">max =</span> pi)</span>
<span id="cb115-10"><a href="#cb115-10" aria-hidden="true" tabindex="-1"></a>  Y <span class="ot">&lt;-</span> (</span>
<span id="cb115-11"><a href="#cb115-11" aria-hidden="true" tabindex="-1"></a>    unif<span class="sc">*</span>unif</span>
<span id="cb115-12"><a href="#cb115-12" aria-hidden="true" tabindex="-1"></a>    <span class="sc">*</span></span>
<span id="cb115-13"><a href="#cb115-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sapply</span>(unif, sin)</span>
<span id="cb115-14"><a href="#cb115-14" aria-hidden="true" tabindex="-1"></a>    <span class="sc">+</span></span>
<span id="cb115-15"><a href="#cb115-15" aria-hidden="true" tabindex="-1"></a>    sigma <span class="sc">*</span> error</span>
<span id="cb115-16"><a href="#cb115-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb115-17"><a href="#cb115-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb115-18"><a href="#cb115-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span> (</span>
<span id="cb115-19"><a href="#cb115-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(</span>
<span id="cb115-20"><a href="#cb115-20" aria-hidden="true" tabindex="-1"></a>      <span class="at">X=</span> unif,</span>
<span id="cb115-21"><a href="#cb115-21" aria-hidden="true" tabindex="-1"></a>      <span class="at">Y =</span> Y</span>
<span id="cb115-22"><a href="#cb115-22" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb115-23"><a href="#cb115-23" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb115-24"><a href="#cb115-24" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb115-25"><a href="#cb115-25" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb115-26"><a href="#cb115-26" aria-hidden="true" tabindex="-1"></a>X_1 <span class="ot">&lt;-</span> <span class="fu">generator</span>(n, sigma_1)</span>
<span id="cb115-27"><a href="#cb115-27" aria-hidden="true" tabindex="-1"></a>X_2 <span class="ot">&lt;-</span> <span class="fu">generator</span>(n, sigma_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="representación-gráfica" class="level2">
<h2 class="anchored" data-anchor-id="representación-gráfica">Representación gráfica</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(X_1) <span class="sc">+</span> </span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>( <span class="fu">aes</span>(X, Y), <span class="at">colour =</span> <span class="st">'black'</span> )<span class="sc">+</span></span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">'Datos con sigma = 0.5'</span>) <span class="sc">+</span></span>
<span id="cb116-4"><a href="#cb116-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> <span class="st">'fun_reg'</span>, <span class="at">linetype =</span> <span class="dv">2</span>)</span>
<span id="cb116-5"><a href="#cb116-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb116-6"><a href="#cb116-6" aria-hidden="true" tabindex="-1"></a>q <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(X_2) <span class="sc">+</span> </span>
<span id="cb116-7"><a href="#cb116-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>( <span class="fu">aes</span>(X, Y), <span class="at">colour =</span> <span class="st">'black'</span> )<span class="sc">+</span></span>
<span id="cb116-8"><a href="#cb116-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">'Datos con sigma = 1'</span>) <span class="sc">+</span></span>
<span id="cb116-9"><a href="#cb116-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> <span class="st">'fun_reg'</span>, <span class="at">linetype =</span> <span class="dv">2</span>)</span>
<span id="cb116-10"><a href="#cb116-10" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>q</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-35-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Puede verse como el sigma aumenta la dispersión respecto al eje Y.</p>
</section>
<section id="ajuste-de-regresión-de-mínimos-cuadrados" class="level2">
<h2 class="anchored" data-anchor-id="ajuste-de-regresión-de-mínimos-cuadrados">Ajuste de regresión de mínimos cuadrados</h2>
<p>Para cada conjunto de datos se pretende ajustar una regresión de mínimos cuadrados penalizada prefijando uno de los grados de libertad efectivos.</p>
</section>
<section id="representación-gráfica-del-error-de-predicción-de-validación-cruzada-generalizando-en-dunción-de-los-grados-de-liberta-utilizados." class="level2">
<h2 class="anchored" data-anchor-id="representación-gráfica-del-error-de-predicción-de-validación-cruzada-generalizando-en-dunción-de-los-grados-de-liberta-utilizados.">Representación gráfica del error de predicción de validación cruzada generalizando en dunción de los grados de liberta utilizados.</h2>
<p>Imprimimos primero algunos ajustes: ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>pinta_spline <span class="ot">&lt;-</span> <span class="cf">function</span> (X, grados_libertad){</span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a>spline_1 <span class="ot">&lt;-</span> <span class="fu">smooth.spline</span>(</span>
<span id="cb118-3"><a href="#cb118-3" aria-hidden="true" tabindex="-1"></a>  X<span class="sc">$</span>X, X<span class="sc">$</span>Y, <span class="at">df =</span> grados_libertad</span>
<span id="cb118-4"><a href="#cb118-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb118-5"><a href="#cb118-5" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb118-6"><a href="#cb118-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> X<span class="sc">$</span>X,</span>
<span id="cb118-7"><a href="#cb118-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> X<span class="sc">$</span>Y,</span>
<span id="cb118-8"><a href="#cb118-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">xfit =</span> spline_1<span class="sc">$</span>x,</span>
<span id="cb118-9"><a href="#cb118-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">yfit =</span> spline_1<span class="sc">$</span>y</span>
<span id="cb118-10"><a href="#cb118-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb118-11"><a href="#cb118-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-12"><a href="#cb118-12" aria-hidden="true" tabindex="-1"></a>titulo <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">'Spline con df = '</span>, grados_libertad)</span>
<span id="cb118-13"><a href="#cb118-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos) <span class="sc">+</span></span>
<span id="cb118-14"><a href="#cb118-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(x, y)) <span class="sc">+</span> </span>
<span id="cb118-15"><a href="#cb118-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(xfit, yfit), <span class="at">color=</span><span class="st">"blue"</span>, <span class="at">size =</span> <span class="fl">1.1</span>) <span class="sc">+</span></span>
<span id="cb118-16"><a href="#cb118-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> <span class="st">'fun_reg'</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb118-17"><a href="#cb118-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(titulo) </span>
<span id="cb118-18"><a href="#cb118-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb118-19"><a href="#cb118-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-20"><a href="#cb118-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>( df <span class="cf">in</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">7</span>,<span class="dv">10</span>, <span class="dv">25</span>) ){</span>
<span id="cb118-21"><a href="#cb118-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">pinta_spline</span>(X_1, df))</span>
<span id="cb118-22"><a href="#cb118-22" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-36-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-36-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-36-4.png" class="img-fluid" width="672"></p>
</div>
<p>::: Bajo una inspección visual puede verse que a mayor número de grados de libertad mejor es el ajuste a los datos utilizados en regresión c, procedamos a costatarlo</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a>cv_error <span class="ot">&lt;-</span> <span class="cf">function</span> (X, grados_libertad){</span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a>  spline_1 <span class="ot">&lt;-</span> <span class="fu">smooth.spline</span>(</span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a>    X<span class="sc">$</span>X, X<span class="sc">$</span>Y, <span class="at">df =</span> grados_libertad</span>
<span id="cb119-4"><a href="#cb119-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb119-5"><a href="#cb119-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span> (spline_1<span class="sc">$</span>cv.crit)</span>
<span id="cb119-6"><a href="#cb119-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb119-7"><a href="#cb119-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-8"><a href="#cb119-8" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">25</span>)</span>
<span id="cb119-9"><a href="#cb119-9" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb119-10"><a href="#cb119-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> df,</span>
<span id="cb119-11"><a href="#cb119-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">y1 =</span> <span class="fu">sapply</span>(df, <span class="cf">function</span>(d)(<span class="fu">cv_error</span>(X_1, d))),</span>
<span id="cb119-12"><a href="#cb119-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">y2 =</span> <span class="fu">sapply</span>(df, <span class="cf">function</span>(d)(<span class="fu">cv_error</span>(X_2, d)))</span>
<span id="cb119-13"><a href="#cb119-13" aria-hidden="true" tabindex="-1"></a>) </span>
<span id="cb119-14"><a href="#cb119-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-15"><a href="#cb119-15" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos) <span class="sc">+</span></span>
<span id="cb119-16"><a href="#cb119-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(x, y1, <span class="at">color=</span><span class="st">"sigma = 0.5"</span>), <span class="at">size =</span> <span class="fl">1.1</span>) <span class="sc">+</span></span>
<span id="cb119-17"><a href="#cb119-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(x, y2, <span class="at">color=</span><span class="st">"sigma = 1"</span>) , <span class="at">size =</span> <span class="fl">1.1</span>) <span class="sc">+</span></span>
<span id="cb119-18"><a href="#cb119-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">'Error y grados de libertad'</span>,</span>
<span id="cb119-19"><a href="#cb119-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">'Grados de libertad'</span>,</span>
<span id="cb119-20"><a href="#cb119-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">'Error de validación cruzada en predicción'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="entrega_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Pasa sigma = 0.5 alcanza un mínimo en "</span>, datos<span class="sc">$</span>x[<span class="fu">which.min</span>(datos<span class="sc">$</span>y1)], <span class="st">" grados de libertad.</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pasa sigma = 0.5 alcanza un mínimo en  15  grados de libertad.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Pasa sigma = 1 alcanza un mínimo en "</span>, datos<span class="sc">$</span>x[<span class="fu">which.min</span>(datos<span class="sc">$</span>y2)], <span class="st">" grados de libertad.</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pasa sigma = 1 alcanza un mínimo en  10  grados de libertad.</code></pre>
</div>
</div>
</section>
<section id="comentario-de-los-resultados" class="level2">
<h2 class="anchored" data-anchor-id="comentario-de-los-resultados">Comentario de los resultados</h2>
<p>Hay varios fenómenos llamativos al observa esta gráfica: 1. Comportamiento general: Decrece, alcanza un mínimo y vuelve a crecer en menor medida. 2. El que los dos gráficos parezcan más o menos desplazados. 3. Que <span class="math inline">\(\sigma\)</span> menor admita más grados de libertad antes de volver a crecer el error. 4. Que la gráfica de <span class="math inline">\(\sigma = 1\)</span> comience a crecer más que la <span class="math inline">\(\sigma = 0.5\)</span>.</p>
<p>Todos estos fenómenos se pueden explicar con la relación entre los errores vista en teoría:</p>
<p><span class="math display">\[
\text{Error}_{Test}
=
\text{Error}_{Training}
+
\frac{2 \sigma^2}{n} \text{grados de libertad}.
\]</span> (Notemos que grados de libertad se corresponde a la traza de la matriz <span class="math inline">\(M\)</span>, que en nuestro caso particular se trata de los mínimos cuadrados)</p>
<section id="comportamiento-general-decrecemiento-mínimo-y-crecimiento-más-lento" class="level3">
<h3 class="anchored" data-anchor-id="comportamiento-general-decrecemiento-mínimo-y-crecimiento-más-lento">Comportamiento general: Decrecemiento, mínimo y crecimiento más lento</h3>
<p>Como rasgo general podemos observar como añadir más grados de libertad mejora el ajuste a los datos de <em>aprendizaje</em>, el error de <em>training</em> está decreciendo en mayor medida que el aumento de grados de libertad. A partir de 10 (o 13 si <span class="math inline">\(\sigma = 1\)</span>) grados puede verse cómo el error de test comienza a crecer de nuevo, este fenómeno conocido como <em>sobreajuste a los datos de entrenamiento</em> no es más que el error de training se disminuye en menor proporción que el peso que suma el término <span class="math inline">\(\frac{2 \sigma^2}{n} \text{grados de libertad}\)</span>.</p>
</section>
<section id="gráficos-desplazados" class="level3">
<h3 class="anchored" data-anchor-id="gráficos-desplazados">Gráficos desplazados</h3>
<p>Esto está motivado por que los <em>datos training</em> de uno es mayor que la de otro. Este fenómenos es natural, ya que por la propia naturaleza de los datos sabemos que los datos de <span class="math inline">\(\sigma = 1\)</span> (la gráfica con mayor error) posee un ruido mayor (concretamente el de <span class="math inline">\(\mathcal{N}(0,1)\)</span>)</p>
</section>
<section id="a-sigma-menor-admita-más-grados-de-libertad-antes-de-volver-a-crecer-el-error." class="level3">
<h3 class="anchored" data-anchor-id="a-sigma-menor-admita-más-grados-de-libertad-antes-de-volver-a-crecer-el-error.">A <span class="math inline">\(\sigma\)</span> menor admita más grados de libertad antes de volver a crecer el error.</h3>
<p>Relacionado con lo anterior, si el <em>ruido</em> es menor será más similar a su desarrollo de Taylor admitiendo por tanto desarrollar más términos de la serie de Taylor (grados de libertad en nuestro caso).</p>
</section>
<section id="cremiento-mayor-del-error-de-sigma-1-frente-a-sigma-0.5" class="level3">
<h3 class="anchored" data-anchor-id="cremiento-mayor-del-error-de-sigma-1-frente-a-sigma-0.5">Cremiento mayor del error de <span class="math inline">\(\sigma = 1\)</span> frente a <span class="math inline">\(\sigma = 0.5\)</span></h3>
<p>Esto es claro resultado del segundo sumando de la relación mostrada:</p>
<p><span class="math display">\[
\frac{2 \sigma^2}{n} \text{grados de libertad}
\]</span> ya que en ambos caso <span class="math inline">\(n\)</span> y <em>grados de libertad</em> son iguales y solo difiere el valor de <span class="math inline">\(\sigma\)</span>.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>